const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.solid,
		C3.Plugins.TiledBg,
		C3.Plugins.Text,
		C3.Behaviors.Physics,
		C3.Plugins.Button,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Behaviors.Bullet,
		C3.Plugins.Audio,
		C3.Plugins.Audio.Cnds.IsAnyPlaying,
		C3.Plugins.System.Acts.WaitForSignal,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Exps.windowwidth,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Text.Acts.SetInstanceVar,
		C3.Plugins.System.Exps.max,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Button.Cnds.OnClicked
	];
};
self.C3_JsPropNameTable = [
	{TV____Overlay: 0},
	{FOODminigame__Button: 0},
	{Garden__Button: 0},
	{Level__Bar: 0},
	{Hunger__Bar: 0},
	{Happiness__Bar: 0},
	{Platform: 0},
	{Platform2: 0},
	{Solid: 0},
	{Caterpillar: 0},
	{Main__Background: 0},
	{Home__Button: 0},
	{Main_Game_Title: 0},
	{Happiness__Bar__Text: 0},
	{hunger_vsr: 0},
	{Hunger__Bar__Text: 0},
	{Level__Bar__Text: 0},
	{Caterpillar__Food__Minigame__BG: 0},
	{Physics: 0},
	{Apple: 0},
	{Garden__BG: 0},
	{Starting__Screen__BG: 0},
	{WELCOME__Button: 0},
	{WELCOME__text: 0},
	{START__Button: 0},
	{Summary__Text: 0},
	{Invisible__Platform: 0},
	{Keyboard: 0},
	{Mouse: 0},
	{Time__FoodMinigame: 0},
	{Sprite2: 0},
	{RottenApple: 0},
	{FOOD_Minigame_Score: 0},
	{barrier_after_30secs: 0},
	{goal: 0},
	{Bullet: 0},
	{Ball: 0},
	{Garden_Minigame_Score: 0},
	{Audio: 0},
	{goal2: 0},
	{FOOD_MINIGAME_INFO: 0},
	{GARDEN_MINIGAME_INFO: 0},
	{Main_Floor: 0},
	{Couch: 0},
	{Window: 0},
	{TIme30: 0},
	{Minigame_Score: 0},
	{Hunger: 0},
	{CanSubtract: 0},
	{Garden_Score: 0},
	{Happiness_Level: 0},
	{Level: 0}
];

self.InstanceType = {
	TV____Overlay: class extends self.ISpriteInstance {},
	FOODminigame__Button: class extends self.ISpriteInstance {},
	Garden__Button: class extends self.ISpriteInstance {},
	Level__Bar: class extends self.ISpriteInstance {},
	Hunger__Bar: class extends self.ISpriteInstance {},
	Happiness__Bar: class extends self.ISpriteInstance {},
	Caterpillar: class extends self.ISpriteInstance {},
	Main__Background: class extends self.ITiledBackgroundInstance {},
	Home__Button: class extends self.ISpriteInstance {},
	Main_Game_Title: class extends self.ITextInstance {},
	Happiness__Bar__Text: class extends self.ITextInstance {},
	Hunger__Bar__Text: class extends self.ITextInstance {},
	Level__Bar__Text: class extends self.ITextInstance {},
	Caterpillar__Food__Minigame__BG: class extends self.ITiledBackgroundInstance {},
	Apple: class extends self.ISpriteInstance {},
	Garden__BG: class extends self.ITiledBackgroundInstance {},
	Starting__Screen__BG: class extends self.ITiledBackgroundInstance {},
	WELCOME__Button: class extends self.ISpriteInstance {},
	WELCOME__text: class extends self.ITextInstance {},
	START__Button: class extends self.IButtonInstance {},
	Summary__Text: class extends self.ITextInstance {},
	Invisible__Platform: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Time__FoodMinigame: class extends self.ITextInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	RottenApple: class extends self.ISpriteInstance {},
	FOOD_Minigame_Score: class extends self.ITextInstance {},
	barrier_after_30secs: class extends self.ISpriteInstance {},
	goal: class extends self.ISpriteInstance {},
	Ball: class extends self.ISpriteInstance {},
	Garden_Minigame_Score: class extends self.ITextInstance {},
	Audio: class extends self.IInstance {},
	goal2: class extends self.ISpriteInstance {},
	FOOD_MINIGAME_INFO: class extends self.ITextInstance {},
	GARDEN_MINIGAME_INFO: class extends self.ITextInstance {},
	Main_Floor: class extends self.ITiledBackgroundInstance {},
	Couch: class extends self.ISpriteInstance {},
	Window: class extends self.ISpriteInstance {}
}