const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Shape3D,
		C3.Behaviors.solid,
		C3.Plugins.Camera3D,
		C3.Behaviors.Pathfinding,
		C3.Plugins.Sprite,
		C3.Behaviors.scrollto,
		C3.Behaviors.Car,
		C3.Plugins.Text,
		C3.Behaviors.Anchor,
		C3.Plugins.Button,
		C3.Plugins.TiledBg,
		C3.Plugins.progressbar,
		C3.Plugins.Audio,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Camera3D.Acts.LookParallelToLayout,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.progressbar.Acts.SetProgress,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.Every,
		C3.Behaviors.Pathfinding.Acts.FindPath,
		C3.Behaviors.Pathfinding.Cnds.OnPathFound,
		C3.Behaviors.Pathfinding.Acts.StartMoving,
		C3.Plugins.Shape3D.Acts.Destroy,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Shape3D.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Shape3D.Acts.SetPos,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.ResetGlobals
	];
};
self.C3_JsPropNameTable = [
	{Solid: 0},
	{wall: 0},
	{"3DCamera": 0},
	{powerOrb: 0},
	{Pathfinding: 0},
	{ENEMY: 0},
	{coin: 0},
	{ScrollTo: 0},
	{Car: 0},
	{Player: 0},
	{wall2: 0},
	{Text: 0},
	{Anchor: 0},
	{lives: 0},
	{coinmeater: 0},
	{Button: 0},
	{Text2: 0},
	{TiledBackground: 0},
	{HP: 0},
	{ProgressBar: 0},
	{audio: 0},
	{arow: 0},
	{Text3: 0},
	{coin2: 0},
	{coin3: 0},
	{trigger: 0},
	{Button2: 0},
	{Text4: 0},
	{Text5: 0},
	{Sprite: 0},
	{heheCoin: 0}
];

self.InstanceType = {
	wall: class extends self.I3DShapeInstance {},
	_3DCamera: class extends self.IInstance {},
	powerOrb: class extends self.I3DShapeInstance {},
	ENEMY: class extends self.I3DShapeInstance {},
	coin: class extends self.I3DShapeInstance {},
	Player: class extends self.ISpriteInstance {},
	wall2: class extends self.I3DShapeInstance {},
	Text: class extends self.ITextInstance {},
	lives: class extends self.ITextInstance {},
	coinmeater: class extends self.ITextInstance {},
	Button: class extends self.IButtonInstance {},
	Text2: class extends self.ITextInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	HP: class extends self.IProgressBarInstance {},
	ProgressBar: class extends self.IProgressBarInstance {},
	audio: class extends self.IInstance {},
	arow: class extends self.ISpriteInstance {},
	Text3: class extends self.ITextInstance {},
	coin2: class extends self.I3DShapeInstance {},
	coin3: class extends self.I3DShapeInstance {},
	trigger: class extends self.ISpriteInstance {},
	Button2: class extends self.IButtonInstance {},
	Text4: class extends self.ITextInstance {},
	Text5: class extends self.ITextInstance {},
	Sprite: class extends self.ISpriteInstance {}
}