const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Text,
		C3.Plugins.Mouse,
		C3.Plugins.Button,
		C3.Behaviors.solid,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.Physics,
		C3.Plugins.Keyboard,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Acts.RestartLayout
	];
};
self.C3_JsPropNameTable = [
	{bgg: 0},
	{mokey: 0},
	{MONKEy: 0},
	{bggg: 0},
	{gameTitle: 0},
	{gameTitle2: 0},
	{tart: 0},
	{Mouse: 0},
	{start: 0},
	{Solid: 0},
	{Sprite6: 0},
	{level2: 0},
	{Platform: 0},
	{ScrollTo: 0},
	{mokney: 0},
	{bggggg: 0},
	{mm2: 0},
	{bannana: 0},
	{Physics: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{restars: 0},
	{Keyboard: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{Text: 0},
	{Sprite3: 0},
	{lives: 0}
];

self.InstanceType = {
	bgg: class extends self.ISpriteInstance {},
	mokey: class extends self.ISpriteInstance {},
	MONKEy: class extends self.ISpriteInstance {},
	bggg: class extends self.ISpriteInstance {},
	gameTitle: class extends self.ITextInstance {},
	gameTitle2: class extends self.ISpriteInstance {},
	tart: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	start: class extends self.IButtonInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	level2: class extends self.IButtonInstance {},
	mokney: class extends self.ISpriteInstance {},
	bggggg: class extends self.ISpriteInstance {},
	mm2: class extends self.ISpriteInstance {},
	bannana: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	restars: class extends self.IButtonInstance {},
	Keyboard: class extends self.IInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Sprite3: class extends self.ISpriteInstance {}
}