const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.scrollto,
		C3.Behaviors.EightDir,
		C3.Behaviors.solid,
		C3.Behaviors.Bullet,
		C3.Plugins.Button,
		C3.Plugins.Keyboard,
		C3.Plugins.Text,
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.TiledBg.Acts.SetImageOffsetY,
		C3.Plugins.TiledBg.Exps.ImageOffsetY,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.RestartLayout
	];
};
self.C3_JsPropNameTable = [
	{ScrollTo: 0},
	{"8Direction": 0},
	{PlayerCar: 0},
	{Solid: 0},
	{Gas: 0},
	{Bullet: 0},
	{Bush: 0},
	{Roadblock: 0},
	{GameTitle: 0},
	{Sprite: 0},
	{StartButton: 0},
	{Keyboard: 0},
	{Points: 0},
	{TextBackground: 0},
	{Lives: 0},
	{TextBackground2: 0},
	{Road: 0},
	{FuelLevel: 0},
	{Textbackground3: 0},
	{Speed: 0},
	{TextBackground4: 0},
	{fuel: 0},
	{LoseScreenBackground: 0},
	{YouLose: 0},
	{TryAgain: 0},
	{RoadSide: 0},
	{ThumbsUp: 0},
	{HighScore: 0},
	{HighScoreBackground: 0},
	{PointsNumber: 0},
	{EnemyCar2: 0},
	{Powerup: 0}
];

self.InstanceType = {
	PlayerCar: class extends self.ISpriteInstance {},
	Gas: class extends self.ISpriteInstance {},
	Bush: class extends self.ISpriteInstance {},
	Roadblock: class extends self.ISpriteInstance {},
	GameTitle: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	StartButton: class extends self.IButtonInstance {},
	Keyboard: class extends self.IInstance {},
	Points: class extends self.ITextInstance {},
	TextBackground: class extends self.ISpriteInstance {},
	Lives: class extends self.ITextInstance {},
	TextBackground2: class extends self.ISpriteInstance {},
	Road: class extends self.ITiledBackgroundInstance {},
	FuelLevel: class extends self.ITextInstance {},
	Textbackground3: class extends self.ISpriteInstance {},
	Speed: class extends self.ITextInstance {},
	TextBackground4: class extends self.ISpriteInstance {},
	fuel: class extends self.ISpriteInstance {},
	LoseScreenBackground: class extends self.ITiledBackgroundInstance {},
	YouLose: class extends self.ISpriteInstance {},
	TryAgain: class extends self.IButtonInstance {},
	RoadSide: class extends self.ISpriteInstance {},
	ThumbsUp: class extends self.ISpriteInstance {},
	HighScore: class extends self.ITextInstance {},
	HighScoreBackground: class extends self.ISpriteInstance {},
	PointsNumber: class extends self.ITextInstance {},
	EnemyCar2: class extends self.ISpriteInstance {}
}