const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Anchor,
		C3.Plugins.TiledBg,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.Flash,
		C3.Behaviors.solid,
		C3.Behaviors.EightDir,
		C3.Behaviors.Bullet,
		C3.Plugins.Text,
		C3.Plugins.Mouse,
		C3.Plugins.Button,
		C3.Plugins.progressbar,
		C3.Plugins.Keyboard,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.Text.Acts.SetVisible
	];
};
self.C3_JsPropNameTable = [
	{HealthPercent: 0},
	{Anchor: 0},
	{healthBar: 0},
	{TiledBackground: 0},
	{TiledBackground2: 0},
	{TiledBackground3: 0},
	{Sprite3: 0},
	{Platform: 0},
	{ScrollTo: 0},
	{Flash: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Solid: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{Sprite2: 0},
	{Sprite9: 0},
	{"8Direction": 0},
	{hero: 0},
	{TiledBackground4: 0},
	{Sprite11: 0},
	{Bullet: 0},
	{venom: 0},
	{TiledBackground5: 0},
	{Sprite12: 0},
	{Text: 0},
	{PlayersHealth: 0},
	{Healthpercent: 0},
	{Sprite13: 0},
	{Mouse: 0},
	{Button2: 0},
	{Sprite14: 0},
	{ProgressBar: 0},
	{Keyboard: 0},
	{Sprite10: 0},
	{Text2: 0},
	{death: 0},
	{kunai: 0},
	{Attack: 0},
	{healthpercent: 0},
	{OponentHealth: 0},
	{playershealth: 0},
	{Orochimaru: 0},
	{Text4: 0},
	{portal: 0},
	{TiledBackground6: 0},
	{NejiHyuga: 0},
	{TiledBackground7: 0},
	{TiledBackground8: 0},
	{Sprite16: 0},
	{Sprite17: 0},
	{round1: 0},
	{villianHealthBar2: 0},
	{gentleFist: 0},
	{TheValleyOfTheEnd: 0},
	{Sprite18: 0},
	{onetailcloack: 0},
	{ProgressBar2: 0},
	{opponentsHealth: 0},
	{"2ndvillainhealthbar": 0},
	{opponentsHealthBar: 0},
	{"2ndopponentsHealth": 0},
	{Sprite19: 0},
	{Sprite20: 0},
	{Sprite21: 0},
	{Sprite22: 0},
	{Sprite: 0},
	{sharigan: 0},
	{eyes: 0},
	{Sprite15: 0},
	{Sprite23: 0},
	{FInalbosshealth: 0},
	{Opponent1Health: 0},
	{Opponent2Health: 0},
	{Health: 0},
	{Finalbosshealth: 0}
];

self.InstanceType = {
	healthBar: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	TiledBackground3: class extends self.ITiledBackgroundInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	hero: class extends self.ISpriteInstance {},
	TiledBackground4: class extends self.ITiledBackgroundInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	venom: class extends self.ISpriteInstance {},
	TiledBackground5: class extends self.ITiledBackgroundInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Healthpercent: class extends self.ITextInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Button2: class extends self.IButtonInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	ProgressBar: class extends self.IProgressBarInstance {},
	Keyboard: class extends self.IInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Text2: class extends self.ITextInstance {},
	death: class extends self.IButtonInstance {},
	kunai: class extends self.ISpriteInstance {},
	Attack: class extends self.IButtonInstance {},
	OponentHealth: class extends self.ISpriteInstance {},
	Orochimaru: class extends self.ITextInstance {},
	Text4: class extends self.ITextInstance {},
	portal: class extends self.ISpriteInstance {},
	TiledBackground6: class extends self.ITiledBackgroundInstance {},
	NejiHyuga: class extends self.ISpriteInstance {},
	TiledBackground7: class extends self.ITiledBackgroundInstance {},
	TiledBackground8: class extends self.ITiledBackgroundInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	round1: class extends self.ITextInstance {},
	villianHealthBar2: class extends self.ISpriteInstance {},
	gentleFist: class extends self.ISpriteInstance {},
	TheValleyOfTheEnd: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	onetailcloack: class extends self.ISpriteInstance {},
	ProgressBar2: class extends self.IProgressBarInstance {},
	_2ndvillainhealthbar: class extends self.ISpriteInstance {},
	_2ndopponentsHealth: class extends self.ITextInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	Sprite21: class extends self.ISpriteInstance {},
	Sprite22: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	sharigan: class extends self.ISpriteInstance {},
	eyes: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Sprite23: class extends self.ISpriteInstance {},
	FInalbosshealth: class extends self.ITextInstance {}
}