const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Button,
		C3.Plugins.Text,
		C3.Plugins.Sprite,
		C3.Plugins.TiledBg,
		C3.Behaviors.MoveTo,
		C3.Plugins.Particles,
		C3.Plugins.Keyboard,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Cnds.CompareTime,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Particles.Acts.SetInitSpeed,
		C3.Plugins.Particles.Acts.SetRate,
		C3.Plugins.Particles.Acts.SetSprayCone,
		C3.Plugins.Particles.Acts.SetTimeout,
		C3.Plugins.System.Acts.StopLoop,
		C3.Plugins.System.Acts.Wait
	];
};
self.C3_JsPropNameTable = [
	{StartGame: 0},
	{Welcometoretrobreathing: 0},
	{instruction: 0},
	{notebook: 0},
	{instructions2: 0},
	{instructions3: 0},
	{instruction4: 0},
	{play: 0},
	{Handpreview: 0},
	{HandOutlineThingy: 0},
	{handstartbutton: 0},
	{handbreathingtext: 0},
	{hotcocoapreview: 0},
	{hotcocoastartbutton: 0},
	{hotcocoatext: 0},
	{rainbowPreview: 0},
	{rainbowstartbutton: 0},
	{rainbowbreathingtext: 0},
	{boxbreathingPreview: 0},
	{boxstartbutton: 0},
	{boxbreathingtext: 0},
	{Handbreathinglogo: 0},
	{instructionbackround: 0},
	{intruction1: 0},
	{MoveTo: 0},
	{Redball: 0},
	{box: 0},
	{steam: 0},
	{cocoabackground: 0},
	{Keyboard: 0},
	{hands: 0},
	{hands3: 0},
	{Button: 0},
	{out: 0},
	{hold: 0},
	{In: 0},
	{ball2: 0},
	{back: 0},
	{BreathIn: 0},
	{BreathOut: 0},
	{restart: 0},
	{Coins: 0},
	{Text: 0},
	{minutes: 0},
	{TimePlayed: 0}
];

self.InstanceType = {
	StartGame: class extends self.IButtonInstance {},
	Welcometoretrobreathing: class extends self.ITextInstance {},
	instruction: class extends self.ITextInstance {},
	notebook: class extends self.ISpriteInstance {},
	instructions2: class extends self.ITextInstance {},
	instructions3: class extends self.ITextInstance {},
	instruction4: class extends self.ITextInstance {},
	play: class extends self.IButtonInstance {},
	Handpreview: class extends self.ISpriteInstance {},
	HandOutlineThingy: class extends self.ISpriteInstance {},
	handstartbutton: class extends self.IButtonInstance {},
	handbreathingtext: class extends self.ITextInstance {},
	hotcocoapreview: class extends self.ISpriteInstance {},
	hotcocoastartbutton: class extends self.IButtonInstance {},
	hotcocoatext: class extends self.ITextInstance {},
	rainbowPreview: class extends self.ISpriteInstance {},
	rainbowstartbutton: class extends self.IButtonInstance {},
	rainbowbreathingtext: class extends self.ITextInstance {},
	boxbreathingPreview: class extends self.ISpriteInstance {},
	boxstartbutton: class extends self.IButtonInstance {},
	boxbreathingtext: class extends self.ITextInstance {},
	Handbreathinglogo: class extends self.ISpriteInstance {},
	instructionbackround: class extends self.ITiledBackgroundInstance {},
	intruction1: class extends self.ITextInstance {},
	Redball: class extends self.ISpriteInstance {},
	box: class extends self.ISpriteInstance {},
	steam: class extends self.IParticlesInstance {},
	cocoabackground: class extends self.ITiledBackgroundInstance {},
	Keyboard: class extends self.IInstance {},
	hands: class extends self.ISpriteInstance {},
	hands3: class extends self.ISpriteInstance {},
	Button: class extends self.IButtonInstance {},
	out: class extends self.ITextInstance {},
	hold: class extends self.ITextInstance {},
	In: class extends self.ITextInstance {},
	ball2: class extends self.ISpriteInstance {},
	back: class extends self.IButtonInstance {},
	BreathIn: class extends self.ITextInstance {},
	BreathOut: class extends self.ITextInstance {},
	restart: class extends self.IButtonInstance {},
	Text: class extends self.ITextInstance {},
	minutes: class extends self.ITextInstance {}
}