const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.scrollto,
		C3.Behaviors.Pin,
		C3.Behaviors.Platform,
		C3.Behaviors.MoveTo,
		C3.Behaviors.Bullet,
		C3.Plugins.Text,
		C3.Plugins.Mouse,
		C3.Behaviors.Anchor,
		C3.Plugins.Button,
		C3.Plugins.progressbar,
		C3.TypeScriptInEvents.EventSheet1_Event1,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Behaviors.MoveTo.Acts.MoveToObject,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Button.Cnds.OnClicked
	];
};
self.C3_JsPropNameTable = [
	{TiledBackground: 0},
	{TiledBackground2: 0},
	{Sprite: 0},
	{Solid: 0},
	{ScrollTo: 0},
	{Sprite2: 0},
	{Pin: 0},
	{alienGun: 0},
	{Platform: 0},
	{ScrollTo2: 0},
	{Platform2: 0},
	{Sprite5: 0},
	{MoveTo: 0},
	{enemy: 0},
	{Bullet: 0},
	{Sprite3: 0},
	{Text: 0},
	{Mouse: 0},
	{Anchor: 0},
	{Text2: 0},
	{Button: 0},
	{ProgressBar: 0},
	{ProgressBar2: 0},
	{lives: 0}
];

self.InstanceType = {
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	alienGun: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	enemy: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Mouse: class extends self.IInstance {},
	Text2: class extends self.ITextInstance {},
	Button: class extends self.IButtonInstance {},
	ProgressBar: class extends self.IProgressBarInstance {},
	ProgressBar2: class extends self.IProgressBarInstance {}
}