const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.Physics,
		C3.Behaviors.scrollto,
		C3.Plugins.Keyboard,
		C3.Behaviors.solid,
		C3.Behaviors.Sin,
		C3.Behaviors.Bullet,
		C3.Behaviors.MoveTo,
		C3.Plugins.Button,
		C3.Plugins.Text,
		C3.Plugins.TiledBg,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Behaviors.Platform.Acts.SetVectorX,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Behaviors.MoveTo.Acts.MoveToObject,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.GoToLayout
	];
};
self.C3_JsPropNameTable = [
	{Platform: 0},
	{Physics: 0},
	{ScrollTo: 0},
	{Player: 0},
	{Keyboard: 0},
	{Solid: 0},
	{floor1: 0},
	{enemy1: 0},
	{Sine: 0},
	{enemy2: 0},
	{enemyShooter: 0},
	{enemyStand: 0},
	{Bullet: 0},
	{bullet: 0},
	{movingEnemyBush: 0},
	{Boss: 0},
	{base: 0},
	{MoveTo: 0},
	{Ball: 0},
	{backround: 0},
	{Start: 0},
	{Instructions: 0},
	{Instructions2: 0},
	{Teleportback: 0},
	{BallWall: 0},
	{Sky: 0},
	{TiledBackground: 0},
	{cloud: 0},
	{Portal: 0},
	{Win: 0},
	{Winbackground: 0},
	{PlayAgain: 0},
	{SpawnBullets: 0}
];

self.InstanceType = {
	Player: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	floor1: class extends self.ISpriteInstance {},
	enemy1: class extends self.ISpriteInstance {},
	enemy2: class extends self.ISpriteInstance {},
	enemyShooter: class extends self.ISpriteInstance {},
	enemyStand: class extends self.ISpriteInstance {},
	bullet: class extends self.ISpriteInstance {},
	movingEnemyBush: class extends self.ISpriteInstance {},
	Boss: class extends self.ISpriteInstance {},
	base: class extends self.ISpriteInstance {},
	Ball: class extends self.ISpriteInstance {},
	backround: class extends self.ISpriteInstance {},
	Start: class extends self.IButtonInstance {},
	Instructions: class extends self.IButtonInstance {},
	Instructions2: class extends self.ITextInstance {},
	Teleportback: class extends self.IButtonInstance {},
	BallWall: class extends self.ISpriteInstance {},
	Sky: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	cloud: class extends self.ISpriteInstance {},
	Portal: class extends self.ISpriteInstance {},
	Win: class extends self.ITextInstance {},
	Winbackground: class extends self.ISpriteInstance {},
	PlayAgain: class extends self.IButtonInstance {}
}