const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Camera3D,
		C3.Plugins.Sprite,
		C3.Behaviors.scrollto,
		C3.Behaviors.Platform,
		C3.Behaviors.solid,
		C3.Plugins.TiledBg,
		C3.Behaviors.Sin,
		C3.Plugins.Text,
		C3.Behaviors.Anchor,
		C3.Plugins.Button,
		C3.Plugins.Keyboard,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.Platform.Acts.SetDoubleJumpEnabled,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.Platform.Acts.ResetDoubleJump,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.ResetGlobals
	];
};
self.C3_JsPropNameTable = [
	{sprite: 0},
	{ScrollTo: 0},
	{Platform: 0},
	{Luizi: 0},
	{Solid: 0},
	{gruond: 0},
	{TiledBackground5: 0},
	{Sine: 0},
	{enemy: 0},
	{Anchor: 0},
	{lives: 0},
	{Button: 0},
	{TiledBackground: 0},
	{TiledBackground3: 0},
	{lava: 0},
	{portal: 0},
	{TiledBackground4: 0},
	{Sprite2: 0},
	{Keyboard: 0},
	{TiledBackground6: 0},
	{TiledBackground7: 0},
	{Sprite3: 0},
	{MysteryPowerupBox: 0},
	{Sprite4: 0},
	{TiledBackground2: 0},
	{Maritzio: 0},
	{PLAYAGAIN: 0},
	{Text: 0},
	{Text2: 0},
	{TiledBackground8: 0},
	{start: 0},
	{Text3: 0},
	{Lives: 0},
	{GameClock: 0},
	{speed: 0}
];

self.InstanceType = {
	sprite: class extends self.IInstance {},
	Luizi: class extends self.ISpriteInstance {},
	gruond: class extends self.ISpriteInstance {},
	TiledBackground5: class extends self.ITiledBackgroundInstance {},
	enemy: class extends self.ISpriteInstance {},
	lives: class extends self.ITextInstance {},
	Button: class extends self.IButtonInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	TiledBackground3: class extends self.ITiledBackgroundInstance {},
	lava: class extends self.ISpriteInstance {},
	portal: class extends self.ISpriteInstance {},
	TiledBackground4: class extends self.ITiledBackgroundInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	TiledBackground6: class extends self.ITiledBackgroundInstance {},
	TiledBackground7: class extends self.ITiledBackgroundInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	MysteryPowerupBox: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	Maritzio: class extends self.ISpriteInstance {},
	PLAYAGAIN: class extends self.IButtonInstance {},
	Text: class extends self.ITextInstance {},
	Text2: class extends self.ITextInstance {},
	TiledBackground8: class extends self.ITiledBackgroundInstance {},
	start: class extends self.IButtonInstance {},
	Text3: class extends self.ITextInstance {}
}