const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Text,
		C3.Plugins.Mouse,
		C3.Plugins.TiledBg,
		C3.Behaviors.DragnDrop,
		C3.Plugins.progressbar,
		C3.Behaviors.Platform,
		C3.Behaviors.solid,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Cnds.CompareTime,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.progressbar.Acts.SetMaximum,
		C3.Plugins.progressbar.Acts.SetProgress,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.progressbar.Cnds.CompareProgress
	];
};
self.C3_JsPropNameTable = [
	{backround1: 0},
	{intructions: 0},
	{start: 0},
	{beginingExt: 0},
	{mouse: 0},
	{backrounbd: 0},
	{intructions24: 0},
	{instuction: 0},
	{buttontoHomescreen: 0},
	{bg: 0},
	{Pet: 0},
	{"12text": 0},
	{eatButton: 0},
	{DragDrop: 0},
	{Brush: 0},
	{toy: 0},
	{text566: 0},
	{bathBack: 0},
	{dog2: 0},
	{sponge: 0},
	{ProgressBar: 0},
	{r: 0},
	{eat: 0},
	{eatiNBowl2: 0},
	{Progress: 0},
	{soap: 0},
	{bathDcreenTxt: 0},
	{cakepop: 0},
	{hearts: 0},
	{toyBack: 0},
	{Platform: 0},
	{dog3: 0},
	{toy2: 0},
	{Solid: 0},
	{platform34: 0},
	{winnerWinner: 0},
	{win: 0},
	{win2: 0},
	{s: 0},
	{medal: 0},
	{back: 0},
	{hatched: 0}
];

self.InstanceType = {
	backround1: class extends self.ISpriteInstance {},
	intructions: class extends self.ITextInstance {},
	start: class extends self.ISpriteInstance {},
	beginingExt: class extends self.ISpriteInstance {},
	mouse: class extends self.IInstance {},
	backrounbd: class extends self.ISpriteInstance {},
	intructions24: class extends self.ITextInstance {},
	instuction: class extends self.ISpriteInstance {},
	buttontoHomescreen: class extends self.ISpriteInstance {},
	bg: class extends self.ITiledBackgroundInstance {},
	Pet: class extends self.ISpriteInstance {},
	_12text: class extends self.ITextInstance {},
	eatButton: class extends self.ISpriteInstance {},
	Brush: class extends self.ISpriteInstance {},
	toy: class extends self.ISpriteInstance {},
	text566: class extends self.ITextInstance {},
	bathBack: class extends self.ITiledBackgroundInstance {},
	dog2: class extends self.ISpriteInstance {},
	sponge: class extends self.ISpriteInstance {},
	ProgressBar: class extends self.IProgressBarInstance {},
	r: class extends self.ISpriteInstance {},
	eat: class extends self.ITiledBackgroundInstance {},
	eatiNBowl2: class extends self.ISpriteInstance {},
	Progress: class extends self.ITextInstance {},
	soap: class extends self.ISpriteInstance {},
	bathDcreenTxt: class extends self.ITextInstance {},
	cakepop: class extends self.ITextInstance {},
	hearts: class extends self.ISpriteInstance {},
	toyBack: class extends self.ITiledBackgroundInstance {},
	dog3: class extends self.ISpriteInstance {},
	toy2: class extends self.ISpriteInstance {},
	platform34: class extends self.ISpriteInstance {},
	winnerWinner: class extends self.ITiledBackgroundInstance {},
	win: class extends self.ITextInstance {},
	win2: class extends self.ITextInstance {},
	s: class extends self.ITextInstance {},
	medal: class extends self.ISpriteInstance {},
	back: class extends self.ISpriteInstance {}
}