const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Pathfinding,
		C3.Behaviors.Pin,
		C3.Behaviors.LOS,
		C3.Behaviors.MoveTo,
		C3.Plugins.Mouse,
		C3.Behaviors.Turret,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Behaviors.scrollto,
		C3.Behaviors.EightDir,
		C3.Plugins.Text,
		C3.Behaviors.Anchor,
		C3.Plugins.Button,
		C3.Plugins.Keyboard,
		C3.Plugins.Audio,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Behaviors.Turret.Acts.AcquireTarget,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Behaviors.Pathfinding.Acts.FindPath,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Pin.Acts.PinByImagePoint,
		C3.Behaviors.Pathfinding.Acts.StartMoving,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Behaviors.Turret.Cnds.OnShoot,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Play
	];
};
self.C3_JsPropNameTable = [
	{AAMap: 0},
	{AllyCastle: 0},
	{AllyFlag: 0},
	{EnemyCastle: 0},
	{EnemyFlag: 0},
	{Dock: 0},
	{health: 0},
	{Pathfinding: 0},
	{zombie: 0},
	{Health: 0},
	{Skeleton: 0},
	{Pin: 0},
	{EnemyTracker: 0},
	{Necromancer: 0},
	{LineOfSight: 0},
	{Witch: 0},
	{ZombieWarrior: 0},
	{MoveTo: 0},
	{EnemyTarget: 0},
	{Mouse: 0},
	{Turret: 0},
	{ArcherTower: 0},
	{Bullet: 0},
	{DestroyOutside: 0},
	{Arrow: 0},
	{Ballista: 0},
	{WARARROW: 0},
	{Catapult: 0},
	{CannonBall: 0},
	{Trebuchet: 0},
	{rock: 0},
	{ScrollTo: 0},
	{"8Direction": 0},
	{camera: 0},
	{Anchor: 0},
	{Waves: 0},
	{Gold: 0},
	{waveCount: 0},
	{ArcherTowerButton: 0},
	{BallistaButton: 0},
	{CatapultButton: 0},
	{TrebuchetButton: 0},
	{Text: 0},
	{Play: 0},
	{Keyboard: 0},
	{Sprite: 0},
	{Audio: 0},
	{Ally_Structural_Integrity: 0},
	{enemies: 0}
];

self.InstanceType = {
	AAMap: class extends self.ISpriteInstance {},
	AllyCastle: class extends self.ISpriteInstance {},
	AllyFlag: class extends self.ISpriteInstance {},
	EnemyCastle: class extends self.ISpriteInstance {},
	EnemyFlag: class extends self.ISpriteInstance {},
	Dock: class extends self.ISpriteInstance {},
	zombie: class extends self.ISpriteInstance {},
	Skeleton: class extends self.ISpriteInstance {},
	EnemyTracker: class extends self.ISpriteInstance {},
	Necromancer: class extends self.ISpriteInstance {},
	Witch: class extends self.ISpriteInstance {},
	ZombieWarrior: class extends self.ISpriteInstance {},
	EnemyTarget: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	ArcherTower: class extends self.ISpriteInstance {},
	Arrow: class extends self.ISpriteInstance {},
	Ballista: class extends self.ISpriteInstance {},
	WARARROW: class extends self.ISpriteInstance {},
	Catapult: class extends self.ISpriteInstance {},
	CannonBall: class extends self.ISpriteInstance {},
	Trebuchet: class extends self.ISpriteInstance {},
	rock: class extends self.ISpriteInstance {},
	camera: class extends self.ISpriteInstance {},
	Waves: class extends self.ITextInstance {},
	Gold: class extends self.ITextInstance {},
	waveCount: class extends self.ISpriteInstance {},
	Health: class extends self.ITextInstance {},
	ArcherTowerButton: class extends self.IButtonInstance {},
	BallistaButton: class extends self.IButtonInstance {},
	CatapultButton: class extends self.IButtonInstance {},
	TrebuchetButton: class extends self.IButtonInstance {},
	Text: class extends self.ITextInstance {},
	Play: class extends self.IButtonInstance {},
	Keyboard: class extends self.IInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {}
}