const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.DragnDrop,
		C3.Plugins.TiledBg,
		C3.Plugins.Text,
		C3.Plugins.Button,
		C3.Plugins.Camera3D,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Exps.right,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Button.Cnds.OnClicked
	];
};
self.C3_JsPropNameTable = [
	{Solid: 0},
	{model: 0},
	{DragDrop: 0},
	{Sprite: 0},
	{instutionsss: 0},
	{Text: 0},
	{Text2: 0},
	{Text3: 0},
	{Button: 0},
	{start: 0},
	{Text4: 0},
	{TiledBackground: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{TiledBackground2: 0},
	{TiledBackground3: 0},
	{Text5: 0},
	{home: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{Sprite13: 0},
	{Sprite14: 0},
	{themeTwo: 0},
	{Button2: 0},
	{Button3: 0},
	{Button4: 0},
	{Button5: 0},
	{emo: 0},
	{Sprite15: 0},
	{caual: 0},
	{rainbow: 0},
	{NONCHALANT: 0},
	{blacKANDWHITE: 0},
	{HMM: 0},
	{Sprite16: 0},
	{Sprite17: 0},
	{Sprite18: 0},
	{Sprite19: 0},
	{Sprite20: 0},
	{Sprite21: 0},
	{Sprite22: 0},
	{Sprite23: 0},
	{Sprite24: 0},
	{Sprite25: 0},
	{Sprite26: 0},
	{Sprite27: 0},
	{timer: 0},
	{TiledBackground4: 0},
	{rating: 0},
	{"3DCamera": 0},
	{TiledBackground5: 0},
	{rate1: 0},
	{rate2: 0},
	{raye3: 0},
	{rate5: 0},
	{rate4: 0},
	{Text6: 0},
	{partypopper: 0},
	{Sprite28: 0},
	{Sprite29: 0},
	{Sprite30: 0},
	{Sprite31: 0},
	{Sprite32: 0},
	{Sprite33: 0},
	{Sprite34: 0},
	{Sprite35: 0},
	{Sprite36: 0},
	{timeleft: 0},
	{timeleft2: 0},
	{timeleft3: 0},
	{timeleft4: 0},
	{timeleft5: 0},
	{timeleft6: 0}
];

self.InstanceType = {
	model: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	instutionsss: class extends self.ITiledBackgroundInstance {},
	Text: class extends self.ITextInstance {},
	Text2: class extends self.ITextInstance {},
	Text3: class extends self.ITextInstance {},
	Button: class extends self.IButtonInstance {},
	start: class extends self.IButtonInstance {},
	Text4: class extends self.ITextInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	TiledBackground3: class extends self.ITiledBackgroundInstance {},
	Text5: class extends self.ITextInstance {},
	home: class extends self.IButtonInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	themeTwo: class extends self.IButtonInstance {},
	Button2: class extends self.IButtonInstance {},
	Button3: class extends self.IButtonInstance {},
	Button4: class extends self.IButtonInstance {},
	Button5: class extends self.IButtonInstance {},
	emo: class extends self.ITextInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	caual: class extends self.ITextInstance {},
	rainbow: class extends self.ITextInstance {},
	NONCHALANT: class extends self.ITextInstance {},
	blacKANDWHITE: class extends self.ITextInstance {},
	HMM: class extends self.ITextInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	Sprite21: class extends self.ISpriteInstance {},
	Sprite22: class extends self.ISpriteInstance {},
	Sprite23: class extends self.ISpriteInstance {},
	Sprite24: class extends self.ISpriteInstance {},
	Sprite25: class extends self.ISpriteInstance {},
	Sprite26: class extends self.ISpriteInstance {},
	Sprite27: class extends self.ISpriteInstance {},
	timer: class extends self.ITextInstance {},
	TiledBackground4: class extends self.ITiledBackgroundInstance {},
	rating: class extends self.ITextInstance {},
	_3DCamera: class extends self.IInstance {},
	TiledBackground5: class extends self.ITiledBackgroundInstance {},
	rate1: class extends self.IButtonInstance {},
	rate2: class extends self.IButtonInstance {},
	raye3: class extends self.IButtonInstance {},
	rate5: class extends self.IButtonInstance {},
	rate4: class extends self.IButtonInstance {},
	Text6: class extends self.ITextInstance {},
	partypopper: class extends self.ISpriteInstance {},
	Sprite28: class extends self.ISpriteInstance {},
	Sprite29: class extends self.ISpriteInstance {},
	Sprite30: class extends self.ISpriteInstance {},
	Sprite31: class extends self.ISpriteInstance {},
	Sprite32: class extends self.ISpriteInstance {},
	Sprite33: class extends self.ISpriteInstance {},
	Sprite34: class extends self.ISpriteInstance {},
	Sprite35: class extends self.ISpriteInstance {},
	Sprite36: class extends self.ISpriteInstance {}
}