const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Text,
		C3.Plugins.Button,
		C3.Plugins.Sprite,
		C3.Behaviors.MoveTo,
		C3.Behaviors.Physics,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.Sin,
		C3.Plugins.Mouse,
		C3.Behaviors.solid,
		C3.Behaviors.Pin,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Behaviors.Physics.Acts.SetEnabled,
		C3.Behaviors.Physics.Acts.ApplyImpulseAtAngle,
		C3.Behaviors.Sin.Exps.Value,
		C3.Plugins.Mouse.Cnds.OnRelease,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.StopAnim
	];
};
self.C3_JsPropNameTable = [
	{InstructionsBackground: 0},
	{Instructionstext: 0},
	{Startgamebutton: 0},
	{MoveTo: 0},
	{Snakecustomer: 0},
	{Nextcustomer: 0},
	{Cafe: 0},
	{Cafebackground: 0},
	{BobaAngle: 0},
	{Physics: 0},
	{DragDrop: 0},
	{Sine: 0},
	{Bobaballs: 0},
	{makeBoba: 0},
	{Slingshotbackground: 0},
	{Mouse: 0},
	{Solid: 0},
	{Bobacup: 0},
	{counter: 0},
	{invisiblebox: 0},
	{spoon: 0},
	{Invisiblebox2: 0},
	{CupWall: 0},
	{Pin: 0},
	{customerOrder: 0},
	{Exitdoorbox: 0},
	{fullcup: 0},
	{Cupandspritecombo: 0},
	{bobaNames: 0},
	{bobaballcount: 0},
	{customeractive: 0}
];

self.InstanceType = {
	InstructionsBackground: class extends self.ITiledBackgroundInstance {},
	Instructionstext: class extends self.ITextInstance {},
	Startgamebutton: class extends self.IButtonInstance {},
	Snakecustomer: class extends self.ISpriteInstance {},
	Nextcustomer: class extends self.IButtonInstance {},
	Cafe: class extends self.ITiledBackgroundInstance {},
	Cafebackground: class extends self.ISpriteInstance {},
	Bobaballs: class extends self.ISpriteInstance {},
	makeBoba: class extends self.IButtonInstance {},
	Slingshotbackground: class extends self.ITiledBackgroundInstance {},
	Mouse: class extends self.IInstance {},
	Bobacup: class extends self.ISpriteInstance {},
	counter: class extends self.ISpriteInstance {},
	invisiblebox: class extends self.ISpriteInstance {},
	spoon: class extends self.ISpriteInstance {},
	Invisiblebox2: class extends self.ISpriteInstance {},
	CupWall: class extends self.ISpriteInstance {},
	customerOrder: class extends self.ITextInstance {},
	Exitdoorbox: class extends self.ISpriteInstance {},
	fullcup: class extends self.ISpriteInstance {},
	Cupandspritecombo: class extends self.ISpriteInstance {},
	bobaNames: class extends self.ITextInstance {}
}