const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Car,
		C3.Plugins.Camera3D,
		C3.Plugins.TiledBg,
		C3.Plugins.Shape3D,
		C3.Behaviors.solid,
		C3.Behaviors.LOS,
		C3.Behaviors.MoveTo,
		C3.Plugins.Text,
		C3.Plugins.Button,
		C3.Behaviors.Anchor,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Shape3D.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Camera3D.Acts.LookParallelToLayout,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Shape3D.Cnds.OnCollision,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.SubVar,
		C3.Behaviors.LOS.Cnds.HasLOSToObject,
		C3.Behaviors.MoveTo.Acts.MoveToObject,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Button.Cnds.OnClicked
	];
};
self.C3_JsPropNameTable = [
	{Car: 0},
	{BRITISHKID: 0},
	{"3DCamera": 0},
	{Floor1: 0},
	{Solid: 0},
	{"3DShape": 0},
	{ENTRANCEFLOOR2: 0},
	{Roof: 0},
	{"3DShape2": 0},
	{LineOfSight: 0},
	{MoveTo: 0},
	{ARCADEMACHINE2: 0},
	{GAMEOVER: 0},
	{RETRY: 0},
	{GAMEOVERSCREENBG: 0},
	{YOUHAVE_LIves: 0},
	{GOAGAIN: 0},
	{Elevator: 0},
	{PHANTOMARCADEMACHINE: 0},
	{"3DShape4": 0},
	{HELLO: 0},
	{KEY: 0},
	{floor45yafyujdyu: 0},
	{Anchor: 0},
	{LIVES: 0},
	{GOODLUCK: 0},
	{goODLUCKS2: 0},
	{FLOOR2: 0},
	{KEYS: 0},
	{POSTER: 0},
	{YOUWIN2: 0},
	{Lives: 0}
];

self.InstanceType = {
	BRITISHKID: class extends self.ISpriteInstance {},
	_3DCamera: class extends self.IInstance {},
	Floor1: class extends self.ITiledBackgroundInstance {},
	_3DShape: class extends self.I3DShapeInstance {},
	ENTRANCEFLOOR2: class extends self.ITiledBackgroundInstance {},
	Roof: class extends self.I3DShapeInstance {},
	_3DShape2: class extends self.I3DShapeInstance {},
	ARCADEMACHINE2: class extends self.I3DShapeInstance {},
	GAMEOVER: class extends self.ITextInstance {},
	RETRY: class extends self.IButtonInstance {},
	GAMEOVERSCREENBG: class extends self.ISpriteInstance {},
	YOUHAVE_LIves: class extends self.ITextInstance {},
	GOAGAIN: class extends self.IButtonInstance {},
	Elevator: class extends self.I3DShapeInstance {},
	PHANTOMARCADEMACHINE: class extends self.I3DShapeInstance {},
	_3DShape4: class extends self.I3DShapeInstance {},
	HELLO: class extends self.ISpriteInstance {},
	KEY: class extends self.I3DShapeInstance {},
	floor45yafyujdyu: class extends self.I3DShapeInstance {},
	LIVES: class extends self.ITextInstance {},
	GOODLUCK: class extends self.ITextInstance {},
	goODLUCKS2: class extends self.IButtonInstance {},
	FLOOR2: class extends self.ITiledBackgroundInstance {},
	KEYS: class extends self.ITextInstance {},
	POSTER: class extends self.I3DShapeInstance {},
	YOUWIN2: class extends self.ITextInstance {}
}