const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Plugins.Sprite,
		C3.Behaviors.EightDir,
		C3.Behaviors.MoveTo,
		C3.Behaviors.Pin,
		C3.Plugins.Keyboard,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Plugins.Text,
		C3.Plugins.Button,
		C3.Plugins.Mouse,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Behaviors.MoveTo.Acts.MoveToObject,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Button.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Behaviors.EightDir.Acts.SetMaxSpeed,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.System.Acts.SetVar
	];
};
self.C3_JsPropNameTable = [
	{Solid: 0},
	{Border: 0},
	{"8Direction": 0},
	{Player: 0},
	{MoveTo: 0},
	{Zombie: 0},
	{grass: 0},
	{Pin: 0},
	{Raygun: 0},
	{Slime: 0},
	{Keyboard: 0},
	{Bullet: 0},
	{DestroyOutside: 0},
	{Text: 0},
	{Slime2: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{EasterEggSlime: 0},
	{Border2: 0},
	{Text2: 0},
	{Text3: 0},
	{TiledBackground: 0},
	{TiledBackground2: 0},
	{Text4: 0},
	{Text5: 0},
	{Text6: 0},
	{yesButtonLose: 0},
	{Button2: 0},
	{TiledBackground3: 0},
	{TiledBackground4: 0},
	{TiledBackground5: 0},
	{shopbro: 0},
	{Mouse: 0},
	{okbuttonshop: 0},
	{goToShop: 0},
	{noButtonShop: 0},
	{TiledBackground6: 0},
	{GoBackButtonEasterEgg: 0},
	{shopbutton: 0},
	{TiledBackground7: 0},
	{TiledBackground8: 0},
	{TiledBackground9: 0},
	{Sprite3: 0},
	{Text7: 0},
	{Sprite5: 0},
	{Text8: 0},
	{Sprite6: 0},
	{Text9: 0},
	{Sprite7: 0},
	{Text10: 0},
	{TiledBackground10: 0},
	{Text11: 0},
	{winButton: 0},
	{TimeText: 0},
	{Health: 0},
	{SlimeSpawnTime: 0},
	{XP: 0},
	{ZombieSpawnTime: 0},
	{TIME2: 0},
	{MaxSpeed: 0},
	{ShootType: 0}
];

self.InstanceType = {
	Border: class extends self.ITiledBackgroundInstance {},
	Player: class extends self.ISpriteInstance {},
	Zombie: class extends self.ISpriteInstance {},
	grass: class extends self.ITiledBackgroundInstance {},
	Raygun: class extends self.ISpriteInstance {},
	Slime: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Bullet: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Slime2: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	EasterEggSlime: class extends self.ISpriteInstance {},
	Border2: class extends self.ITiledBackgroundInstance {},
	Text2: class extends self.ITextInstance {},
	Text3: class extends self.ITextInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	Text4: class extends self.ITextInstance {},
	Text5: class extends self.ITextInstance {},
	Text6: class extends self.ITextInstance {},
	yesButtonLose: class extends self.IButtonInstance {},
	Button2: class extends self.IButtonInstance {},
	TiledBackground3: class extends self.ITiledBackgroundInstance {},
	TiledBackground4: class extends self.ITiledBackgroundInstance {},
	TiledBackground5: class extends self.ITiledBackgroundInstance {},
	shopbro: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	okbuttonshop: class extends self.IButtonInstance {},
	goToShop: class extends self.ITextInstance {},
	noButtonShop: class extends self.IButtonInstance {},
	TiledBackground6: class extends self.ITiledBackgroundInstance {},
	GoBackButtonEasterEgg: class extends self.IButtonInstance {},
	shopbutton: class extends self.IButtonInstance {},
	TiledBackground7: class extends self.ITiledBackgroundInstance {},
	TiledBackground8: class extends self.ITiledBackgroundInstance {},
	TiledBackground9: class extends self.ITiledBackgroundInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Text7: class extends self.ITextInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Text8: class extends self.ITextInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Text9: class extends self.ITextInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Text10: class extends self.ITextInstance {},
	TiledBackground10: class extends self.ITiledBackgroundInstance {},
	Text11: class extends self.ITextInstance {},
	winButton: class extends self.IButtonInstance {},
	TimeText: class extends self.ITextInstance {}
}