const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.solid,
		C3.Plugins.TiledBg,
		C3.Behaviors.Bullet,
		C3.Plugins.Text,
		C3.Plugins.Button,
		C3.Behaviors.Sin,
		C3.Plugins.Audio,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Behaviors.Platform.Cnds.OnJump
	];
};
self.C3_JsPropNameTable = [
	{Sprite: 0},
	{Platform: 0},
	{Solid: 0},
	{Sprite2: 0},
	{TiledBackground3: 0},
	{Sprite3: 0},
	{Bullet: 0},
	{Bullet2: 0},
	{Bullet3: 0},
	{candy: 0},
	{bomb: 0},
	{Text: 0},
	{Text2: 0},
	{Button: 0},
	{starPage: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{TiledBackground2: 0},
	{TiledBackground4: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{Sine: 0},
	{Sprite9: 0},
	{Button2: 0},
	{Sprite10: 0},
	{Text3: 0},
	{Sprite15: 0},
	{Sprite13: 0},
	{Button4: 0},
	{Button3: 0},
	{Audio: 0},
	{Sprite14: 0},
	{Button5: 0},
	{Lives: 0},
	{Value: 0}
];

self.InstanceType = {
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	TiledBackground3: class extends self.ITiledBackgroundInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	candy: class extends self.ISpriteInstance {},
	bomb: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Text2: class extends self.ITextInstance {},
	Button: class extends self.IButtonInstance {},
	starPage: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	TiledBackground4: class extends self.ITiledBackgroundInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Button2: class extends self.IButtonInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Text3: class extends self.ITextInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Button4: class extends self.IButtonInstance {},
	Button3: class extends self.IButtonInstance {},
	Audio: class extends self.IInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Button5: class extends self.IButtonInstance {}
}