const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.TiledBg,
		C3.Behaviors.scrollto,
		C3.Behaviors.Platform,
		C3.Behaviors.solid,
		C3.Behaviors.Bullet,
		C3.Behaviors.Turret,
		C3.Behaviors.Sin,
		C3.Plugins.Text,
		C3.Behaviors.Anchor,
		C3.Plugins.Button,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Turret.Acts.AddTarget,
		C3.Behaviors.Turret.Cnds.OnShoot,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.CompareVar
	];
};
self.C3_JsPropNameTable = [
	{Sprite: 0},
	{TiledBackground2: 0},
	{ScrollTo: 0},
	{Platform: 0},
	{bobespongaElJugador: 0},
	{Solid: 0},
	{Sprite3: 0},
	{Sprite2: 0},
	{Bullet: 0},
	{Sprite4: 0},
	{Turret: 0},
	{Sprite5: 0},
	{Sine: 0},
	{Sprite6: 0},
	{Anchor: 0},
	{lives: 0},
	{Text: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{button: 0},
	{Sprite11: 0},
	{backgroundwithflowersandbubblesvector: 0},
	{ditupv24d013aa70f00449dbfc87c64a5c3217e: 0},
	{Sprite12: 0},
	{Text2: 0},
	{Sprite13: 0},
	{Sprite14: 0},
	{Lives: 0},
	{burgers: 0}
];

self.InstanceType = {
	Sprite: class extends self.ISpriteInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	bobespongaElJugador: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	lives: class extends self.ITextInstance {},
	Text: class extends self.ITextInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	button: class extends self.IButtonInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	backgroundwithflowersandbubblesvector: class extends self.ISpriteInstance {},
	ditupv24d013aa70f00449dbfc87c64a5c3217e: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Text2: class extends self.ITextInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {}
}