const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.Follow,
		C3.Behaviors.Pathfinding,
		C3.Plugins.Button,
		C3.Plugins.Text,
		C3.Plugins.progressbar,
		C3.Plugins.TiledBg,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.Follow.Acts.FollowObject,
		C3.Behaviors.Follow.Acts.SetDelay,
		C3.Behaviors.Follow.Acts.StopFollowing,
		C3.Behaviors.Pathfinding.Acts.FindPath,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Button.Cnds.OnClicked
	];
};
self.C3_JsPropNameTable = [
	{Sprite: 0},
	{DragDrop: 0},
	{Sprite2: 0},
	{Follow: 0},
	{Pathfinding: 0},
	{dog: 0},
	{Button: 0},
	{Sprite3: 0},
	{Text: 0},
	{healthBar: 0},
	{ProgressBar: 0},
	{Text2: 0},
	{Text3: 0},
	{TiledBackground: 0},
	{TiledBackground2: 0},
	{backround: 0},
	{Text4: 0},
	{win: 0},
	{loss: 0},
	{lose: 0},
	{health: 0},
	{age: 0},
	{ages: 0},
	{Sprite4: 0},
	{Age: 0}
];

self.InstanceType = {
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	dog: class extends self.ISpriteInstance {},
	Button: class extends self.IButtonInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	ProgressBar: class extends self.IProgressBarInstance {},
	Text2: class extends self.ITextInstance {},
	Text3: class extends self.ITextInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	backround: class extends self.ISpriteInstance {},
	Text4: class extends self.ITextInstance {},
	win: class extends self.IButtonInstance {},
	loss: class extends self.IButtonInstance {},
	lose: class extends self.ITextInstance {},
	health: class extends self.ITextInstance {},
	age: class extends self.ISpriteInstance {},
	ages: class extends self.ITextInstance {},
	Sprite4: class extends self.ISpriteInstance {}
}