const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.Follow,
		C3.Behaviors.scrollto,
		C3.Behaviors.solid,
		C3.Plugins.Keyboard,
		C3.Behaviors.Sin,
		C3.Plugins.TiledBg,
		C3.Plugins.Text,
		C3.Plugins.Button,
		C3.Behaviors.Anchor,
		C3.Plugins.Audio,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Behaviors.Platform.Cnds.OnJump,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.MoveAtAngle,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Play
	];
};
self.C3_JsPropNameTable = [
	{Platform: 0},
	{Follow: 0},
	{ScrollTo: 0},
	{Sprite4: 0},
	{Solid: 0},
	{Sprite: 0},
	{Keyboard: 0},
	{Sprite2: 0},
	{Sprite5: 0},
	{Sine: 0},
	{Sprite6: 0},
	{TiledBackground: 0},
	{TiledBackground2: 0},
	{Sprite3: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{Sprite11: 0},
	{Text: 0},
	{Text2: 0},
	{Button: 0},
	{Sprite12: 0},
	{Text3: 0},
	{Sprite13: 0},
	{TiledBackground3: 0},
	{Sprite14: 0},
	{Button2: 0},
	{Sprite15: 0},
	{Text4: 0},
	{Anchor: 0},
	{Text5: 0},
	{Sprite16: 0},
	{Button3: 0},
	{Sprite17: 0},
	{Sprite18: 0},
	{Sprite19: 0},
	{TiledBackground4: 0},
	{Sprite20: 0},
	{Sprite21: 0},
	{Audio: 0},
	{Sprite22: 0},
	{Button4: 0},
	{lives: 0}
];

self.InstanceType = {
	Sprite4: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Text2: class extends self.ITextInstance {},
	Button: class extends self.IButtonInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Text3: class extends self.ITextInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	TiledBackground3: class extends self.ITiledBackgroundInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Button2: class extends self.IButtonInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Text4: class extends self.ITextInstance {},
	Text5: class extends self.ITextInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Button3: class extends self.IButtonInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	TiledBackground4: class extends self.ITiledBackgroundInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	Sprite21: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Sprite22: class extends self.ISpriteInstance {},
	Button4: class extends self.IButtonInstance {}
}