const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.bound,
		C3.Behaviors.EightDir,
		C3.Behaviors.Sin,
		C3.Behaviors.solid,
		C3.Plugins.Keyboard,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Plugins.TiledBg,
		C3.Behaviors.Turret,
		C3.Plugins.Particles,
		C3.Plugins.Text,
		C3.Behaviors.Anchor,
		C3.Plugins.Button,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.MoveAtAngle,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.TiledBg.Acts.SetImageOffsetY,
		C3.Plugins.TiledBg.Exps.ImageOffsetY,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Button.Cnds.OnClicked
	];
};
self.C3_JsPropNameTable = [
	{BoundToLayout: 0},
	{"8Direction": 0},
	{spaceball: 0},
	{Sine: 0},
	{spacecrusader: 0},
	{meteor: 0},
	{Solid: 0},
	{block: 0},
	{keyboard: 0},
	{Bullet: 0},
	{DestroyOutsideLayout: 0},
	{bullet: 0},
	{Stars: 0},
	{Turret: 0},
	{enemybullet: 0},
	{EnemyXplosion: 0},
	{Anchor: 0},
	{lives: 0},
	{RETRY: 0},
	{GAMEOVER: 0},
	{Sprite: 0},
	{megaspacecrusader: 0},
	{bigspacecrusader: 0},
	{introstarz: 0},
	{introtxt: 0},
	{play: 0},
	{xplosion2: 0},
	{blue: 0},
	{bulletcooldown: 0},
	{LIVESM: 0},
	{EnemiesRemaining: 0},
	{bulletcooldown2: 0},
	{LIVESM2: 0},
	{EnemiesRemaining2: 0}
];

self.InstanceType = {
	spaceball: class extends self.ISpriteInstance {},
	spacecrusader: class extends self.ISpriteInstance {},
	meteor: class extends self.ISpriteInstance {},
	block: class extends self.ISpriteInstance {},
	keyboard: class extends self.IInstance {},
	bullet: class extends self.ISpriteInstance {},
	Stars: class extends self.ITiledBackgroundInstance {},
	enemybullet: class extends self.ISpriteInstance {},
	EnemyXplosion: class extends self.IParticlesInstance {},
	lives: class extends self.ITextInstance {},
	RETRY: class extends self.IButtonInstance {},
	GAMEOVER: class extends self.ITextInstance {},
	Sprite: class extends self.ISpriteInstance {},
	megaspacecrusader: class extends self.ISpriteInstance {},
	bigspacecrusader: class extends self.ISpriteInstance {},
	introstarz: class extends self.ISpriteInstance {},
	introtxt: class extends self.ITextInstance {},
	play: class extends self.IButtonInstance {},
	xplosion2: class extends self.ISpriteInstance {},
	blue: class extends self.IParticlesInstance {}
}