const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.scrollto,
		C3.Behaviors.Sin,
		C3.Behaviors.Platform,
		C3.Plugins.Button,
		C3.Plugins.Keyboard,
		C3.Plugins.Text,
		C3.Behaviors.Anchor,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.scrollto.Acts.SetEnabled,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Exps.choose,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.Text.Cnds.OnCreated,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.ResetGlobals
	];
};
self.C3_JsPropNameTable = [
	{background: 0},
	{Backround: 0},
	{Backrgound: 0},
	{Solid: 0},
	{platform: 0},
	{ScrollTo: 0},
	{Sine: 0},
	{Platform: 0},
	{Maincatsprite: 0},
	{cat2: 0},
	{cat3: 0},
	{button: 0},
	{keyboard: 0},
	{Sprite: 0},
	{kjjvhb: 0},
	{TiledBackground: 0},
	{Sprite2: 0},
	{playAgianButton: 0},
	{Anchor: 0},
	{lives: 0},
	{Sprite3: 0},
	{playagain: 0},
	{backrgroundupper: 0},
	{upperbackrgound: 0},
	{Sidebackground: 0},
	{side2: 0},
	{wall2: 0},
	{SpawnHieght: 0},
	{catdroped: 0},
	{TimeLeft: 0}
];

self.InstanceType = {
	background: class extends self.ITiledBackgroundInstance {},
	Backround: class extends self.ITiledBackgroundInstance {},
	Backrgound: class extends self.ISpriteInstance {},
	platform: class extends self.ITiledBackgroundInstance {},
	Maincatsprite: class extends self.ISpriteInstance {},
	cat2: class extends self.ISpriteInstance {},
	cat3: class extends self.ISpriteInstance {},
	button: class extends self.IButtonInstance {},
	keyboard: class extends self.IInstance {},
	Sprite: class extends self.ISpriteInstance {},
	kjjvhb: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	playAgianButton: class extends self.IButtonInstance {},
	lives: class extends self.ITextInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	playagain: class extends self.IButtonInstance {},
	backrgroundupper: class extends self.ITiledBackgroundInstance {},
	upperbackrgound: class extends self.ISpriteInstance {},
	Sidebackground: class extends self.ISpriteInstance {},
	side2: class extends self.ISpriteInstance {},
	wall2: class extends self.ISpriteInstance {}
}