const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Text,
		C3.Plugins.Button,
		C3.Behaviors.solid,
		C3.Plugins.Mouse,
		C3.Behaviors.DragnDrop,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.DragnDrop.Cnds.IsDragging,
		C3.Plugins.Sprite.Exps.Opacity,
		C3.Plugins.Sprite.Acts.SetVisible
	];
};
self.C3_JsPropNameTable = [
	{backround1: 0},
	{startText: 0},
	{startbutton: 0},
	{Sprite: 0},
	{rules: 0},
	{ready: 0},
	{instructions: 0},
	{Solid: 0},
	{girl: 0},
	{Mouse: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{table: 0},
	{DragDrop: 0},
	{bodyoil: 0},
	{mask: 0},
	{many: 0},
	{facemask: 0},
	{Button: 0},
	{Text: 0},
	{Text2: 0},
	{lip: 0},
	{Sprite4: 0},
	{Text3: 0},
	{Text4: 0},
	{girl2: 0},
	{TONER: 0},
	{Sprite5: 0},
	{conceler: 0},
	{FOUNDATION: 0},
	{Text5: 0},
	{manymakwup: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{girlThreee: 0},
	{fadingOutFoundation: 0},
	{Text6: 0},
	{lashes: 0},
	{concealeron: 0},
	{eyelash: 0},
	{conceal: 0},
	{conceal2: 0},
	{Text7: 0},
	{Sprite8: 0},
	{Text8: 0},
	{Text9: 0}
];

self.InstanceType = {
	backround1: class extends self.ISpriteInstance {},
	startText: class extends self.ITextInstance {},
	startbutton: class extends self.IButtonInstance {},
	Sprite: class extends self.ISpriteInstance {},
	rules: class extends self.ITextInstance {},
	ready: class extends self.IButtonInstance {},
	instructions: class extends self.ITextInstance {},
	girl: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	table: class extends self.ISpriteInstance {},
	bodyoil: class extends self.ISpriteInstance {},
	mask: class extends self.ISpriteInstance {},
	many: class extends self.ISpriteInstance {},
	facemask: class extends self.ISpriteInstance {},
	Button: class extends self.IButtonInstance {},
	Text: class extends self.ITextInstance {},
	Text2: class extends self.ITextInstance {},
	lip: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Text3: class extends self.ITextInstance {},
	Text4: class extends self.ITextInstance {},
	girl2: class extends self.ISpriteInstance {},
	TONER: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	conceler: class extends self.ISpriteInstance {},
	FOUNDATION: class extends self.ISpriteInstance {},
	Text5: class extends self.ITextInstance {},
	manymakwup: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	girlThreee: class extends self.ISpriteInstance {},
	fadingOutFoundation: class extends self.ISpriteInstance {},
	Text6: class extends self.ITextInstance {},
	lashes: class extends self.ISpriteInstance {},
	concealeron: class extends self.ISpriteInstance {},
	eyelash: class extends self.ITextInstance {},
	conceal: class extends self.ISpriteInstance {},
	conceal2: class extends self.ITextInstance {},
	Text7: class extends self.ITextInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Text8: class extends self.ITextInstance {},
	Text9: class extends self.ITextInstance {}
}