const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.EightDir,
		C3.Behaviors.scrollto,
		C3.Behaviors.Follow,
		C3.Plugins.Text,
		C3.Behaviors.Anchor,
		C3.Plugins.Button,
		C3.Behaviors.solid,
		C3.Plugins.TiledBg,
		C3.Behaviors.shadowcaster,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.Every,
		C3.Behaviors.Follow.Acts.FollowObject,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.ResetGlobals
	];
};
self.C3_JsPropNameTable = [
	{"8Direction": 0},
	{ScrollTo: 0},
	{Penguin: 0},
	{Background: 0},
	{Follow: 0},
	{PolarBear: 0},
	{fish: 0},
	{Anchor: 0},
	{Lives: 0},
	{Snowballs: 0},
	{Score: 0},
	{IntroductionBackground: 0},
	{Introduction: 0},
	{IntroText: 0},
	{Play: 0},
	{PenguinIntro: 0},
	{Solid: 0},
	{Sprite: 0},
	{bgGameOver: 0},
	{Gameovertext: 0},
	{Restart: 0},
	{IceCube: 0},
	{ShadowCaster: 0},
	{goingthroughsolid: 0},
	{DoorLV1: 0},
	{level2bg: 0},
	{DoorLV2: 0},
	{Secret: 0},
	{SecretBG: 0},
	{level3BG: 0},
	{DoorEscape: 0},
	{BgWIN: 0},
	{FLOOR3: 0},
	{Text: 0},
	{YOUWIN: 0},
	{RESTART1: 0},
	{Snowballscollected: 0}
];

self.InstanceType = {
	Penguin: class extends self.ISpriteInstance {},
	Background: class extends self.ISpriteInstance {},
	PolarBear: class extends self.ISpriteInstance {},
	fish: class extends self.ISpriteInstance {},
	Lives: class extends self.ITextInstance {},
	Snowballs: class extends self.ISpriteInstance {},
	Score: class extends self.ITextInstance {},
	IntroductionBackground: class extends self.ISpriteInstance {},
	Introduction: class extends self.ISpriteInstance {},
	IntroText: class extends self.ITextInstance {},
	Play: class extends self.IButtonInstance {},
	PenguinIntro: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	bgGameOver: class extends self.ITiledBackgroundInstance {},
	Gameovertext: class extends self.ITextInstance {},
	Restart: class extends self.IButtonInstance {},
	IceCube: class extends self.ISpriteInstance {},
	goingthroughsolid: class extends self.ISpriteInstance {},
	DoorLV1: class extends self.ISpriteInstance {},
	level2bg: class extends self.ISpriteInstance {},
	DoorLV2: class extends self.ISpriteInstance {},
	Secret: class extends self.ISpriteInstance {},
	SecretBG: class extends self.ISpriteInstance {},
	level3BG: class extends self.ISpriteInstance {},
	DoorEscape: class extends self.ISpriteInstance {},
	BgWIN: class extends self.ISpriteInstance {},
	FLOOR3: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	YOUWIN: class extends self.ITextInstance {},
	RESTART1: class extends self.IButtonInstance {}
}