const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.TiledBg,
		C3.Plugins.Button,
		C3.Plugins.Text,
		C3.Behaviors.solid,
		C3.Behaviors.scrollto,
		C3.Behaviors.Platform,
		C3.Plugins.Keyboard,
		C3.Behaviors.Timer,
		C3.Behaviors.Anchor,
		C3.Plugins.Cryptography,
		C3.Behaviors.Pin,
		C3.Plugins.Tilemap,
		C3.Behaviors.Rotate,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Button.Acts.SetVisible,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Sprite.Cnds.OnDestroyed
	];
};
self.C3_JsPropNameTable = [
	{Sprite: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{TiledBackground: 0},
	{TiledBackground2: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{StartPlay: 0},
	{Text: 0},
	{PlayerSelect: 0},
	{Sprite7: 0},
	{"2Player": 0},
	{"3Player": 0},
	{Sprite6: 0},
	{Map1Button: 0},
	{Map2Button: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{cloud: 0},
	{cloudButBetter: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{TiledBackground3: 0},
	{iceSelect: 0},
	{Sprite13: 0},
	{desertselect: 0},
	{Sprite14: 0},
	{Solid: 0},
	{snowMapFloor: 0},
	{Map3Button: 0},
	{Sprite15: 0},
	{TiledBackground4: 0},
	{Sprite16: 0},
	{ScrollTo: 0},
	{Platform: 0},
	{testplayer: 0},
	{icemapstepplatform: 0},
	{icemapplatforms: 0},
	{iceTree1: 0},
	{iceTree2: 0},
	{icemapsky: 0},
	{pyramidBackground: 0},
	{desertMapBackground: 0},
	{TiledBackground5: 0},
	{desertground: 0},
	{desertplatforms: 0},
	{Iceselec: 0},
	{testplayer2: 0},
	{Keyboard: 0},
	{ddesertmapplatform: 0},
	{desertmappole: 0},
	{desertmapwalls: 0},
	{desertmapbackground1: 0},
	{desertsky: 0},
	{Sprite17: 0},
	{Cactusdesert: 0},
	{Timer: 0},
	{Anchor: 0},
	{Times: 0},
	{forestmapground: 0},
	{Forestmapplatforms: 0},
	{forestbackground: 0},
	{forestmaptree1: 0},
	{forestmaptree2: 0},
	{forestwalls: 0},
	{forestgroundexend: 0},
	{RedWin: 0},
	{WIn: 0},
	{BlueWin: 0},
	{Textt: 0},
	{Text2: 0},
	{Sprite18: 0},
	{Sprite19: 0},
	{Text3: 0},
	{Cryptography: 0},
	{Pin: 0},
	{Sprite20: 0},
	{Sprite21: 0},
	{Sprite22: 0},
	{Button: 0},
	{Button2: 0},
	{Sprite23: 0},
	{Tilemap: 0},
	{TiledBackground6: 0},
	{Rotate: 0},
	{Text4: 0},
	{Sprite24: 0},
	{Text5: 0},
	{Sprite25: 0},
	{PlayTime: 0}
];

self.InstanceType = {
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	StartPlay: class extends self.IButtonInstance {},
	Text: class extends self.ITextInstance {},
	PlayerSelect: class extends self.ITextInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	_2Player: class extends self.IButtonInstance {},
	_3Player: class extends self.IButtonInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Map1Button: class extends self.IButtonInstance {},
	Map2Button: class extends self.IButtonInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	cloud: class extends self.ISpriteInstance {},
	cloudButBetter: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	TiledBackground3: class extends self.ITiledBackgroundInstance {},
	iceSelect: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	desertselect: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	snowMapFloor: class extends self.ISpriteInstance {},
	Map3Button: class extends self.IButtonInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	TiledBackground4: class extends self.ITiledBackgroundInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	testplayer: class extends self.ISpriteInstance {},
	icemapstepplatform: class extends self.ISpriteInstance {},
	icemapplatforms: class extends self.ISpriteInstance {},
	iceTree1: class extends self.ISpriteInstance {},
	iceTree2: class extends self.ISpriteInstance {},
	icemapsky: class extends self.ITiledBackgroundInstance {},
	pyramidBackground: class extends self.ITiledBackgroundInstance {},
	desertMapBackground: class extends self.ISpriteInstance {},
	TiledBackground5: class extends self.ITiledBackgroundInstance {},
	desertground: class extends self.ISpriteInstance {},
	desertplatforms: class extends self.ISpriteInstance {},
	Iceselec: class extends self.IButtonInstance {},
	testplayer2: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	ddesertmapplatform: class extends self.ISpriteInstance {},
	desertmappole: class extends self.ISpriteInstance {},
	desertmapwalls: class extends self.ISpriteInstance {},
	desertmapbackground1: class extends self.ISpriteInstance {},
	desertsky: class extends self.ITiledBackgroundInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	Cactusdesert: class extends self.ISpriteInstance {},
	Times: class extends self.ITextInstance {},
	forestmapground: class extends self.ISpriteInstance {},
	Forestmapplatforms: class extends self.ISpriteInstance {},
	forestbackground: class extends self.ITiledBackgroundInstance {},
	forestmaptree1: class extends self.ISpriteInstance {},
	forestmaptree2: class extends self.ISpriteInstance {},
	forestwalls: class extends self.ISpriteInstance {},
	forestgroundexend: class extends self.ISpriteInstance {},
	RedWin: class extends self.ISpriteInstance {},
	WIn: class extends self.ISpriteInstance {},
	BlueWin: class extends self.ISpriteInstance {},
	Textt: class extends self.ITextInstance {},
	Text2: class extends self.ITextInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	Text3: class extends self.ITextInstance {},
	Cryptography: class extends self.IInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	Sprite21: class extends self.ISpriteInstance {},
	Sprite22: class extends self.ISpriteInstance {},
	Button: class extends self.IButtonInstance {},
	Button2: class extends self.IButtonInstance {},
	Sprite23: class extends self.ISpriteInstance {},
	Tilemap: class extends self.ITilemapInstance {},
	TiledBackground6: class extends self.ITiledBackgroundInstance {},
	Text4: class extends self.ITextInstance {},
	Sprite24: class extends self.ISpriteInstance {},
	Text5: class extends self.ITextInstance {},
	Sprite25: class extends self.ISpriteInstance {}
}