const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.Follow,
		C3.Behaviors.Pin,
		C3.Plugins.TiledBg,
		C3.Plugins.Camera3D,
		C3.Plugins.Text,
		C3.Plugins.Tilemap,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Follow.Acts.FollowObject,
		C3.Plugins.System.Acts.GoToLayout
	];
};
self.C3_JsPropNameTable = [
	{Solid: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{Platform: 0},
	{ScrollTo: 0},
	{Sprite3: 0},
	{Follow: 0},
	{Sprite4: 0},
	{Pin: 0},
	{Sprite5: 0},
	{Pin2: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{TiledBackground: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{"3DCamera": 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{Sprite13: 0},
	{Text: 0},
	{Text2: 0},
	{Text3: 0},
	{Sprite14: 0},
	{background: 0},
	{Tilemap: 0},
	{Sprite15: 0},
	{Sprite16: 0},
	{Sprite17: 0},
	{Text4: 0},
	{Sprite18: 0},
	{Sprite19: 0},
	{Sprite20: 0},
	{Sprite21: 0}
];

self.InstanceType = {
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	_3DCamera: class extends self.IInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Text2: class extends self.ITextInstance {},
	Text3: class extends self.ITextInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	background: class extends self.ISpriteInstance {},
	Tilemap: class extends self.ITilemapInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	Text4: class extends self.ITextInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	Sprite21: class extends self.ISpriteInstance {}
}