const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Text,
		C3.Plugins.Keyboard,
		C3.Plugins.TextBox,
		C3.Plugins.Sprite,
		C3.Plugins.Mouse,
		C3.Plugins.Dictionary,
		C3.Plugins.Json,
		C3.Plugins.Button,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Text.Cnds.PickDistance,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Mouse.Cnds.OnRelease,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Dictionary.Acts.AddKey,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Dictionary.Exps.Get,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.Signal,
		C3.Plugins.System.Cnds.OnSignal,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Acts.GoToLayout
	];
};
self.C3_JsPropNameTable = [
	{PlayerChooseBackround: 0},
	{HowManyPlayers: 0},
	{Keyboard: 0},
	{"3playerBackround": 0},
	{Player1: 0},
	{Player2: 0},
	{Player3: 0},
	{GameBR: 0},
	{PlayerID: 0},
	{Player1Guess: 0},
	{Player2Guess: 0},
	{Player3Guess: 0},
	{Mouse: 0},
	{Player1Word: 0},
	{YourWordIs1: 0},
	{Dictionary: 0},
	{Player2WordBR: 0},
	{YourWordIs2: 0},
	{Player3WordBR: 0},
	{YourWordIs3: 0},
	{Word1: 0},
	{JSON: 0},
	{Button: 0},
	{Word2: 0},
	{Word3: 0},
	{P1NAME: 0},
	{InstructionsBR: 0},
	{HowToPlay: 0},
	{H2P1: 0},
	{DontLetAnyoneSee: 0},
	{H2P2: 0},
	{Text: 0},
	{MoveToNext: 0},
	{GoAround: 0},
	{Repeat: 0},
	{Point: 0},
	{Majority: 0},
	{P1: 0},
	{p2: 0},
	{P3: 0},
	{NNext: 0},
	{TankYou: 0},
	{T1: 0},
	{cabybara: 0},
	{Bow: 0},
	{Gavin: 0},
	{Kiss: 0},
	{can: 0},
	{Name: 0},
	{Lock: 0},
	{Player1Name: 0},
	{Player2Name: 0},
	{Player3name: 0},
	{ChosenWord: 0},
	{ChosenKey: 0},
	{OddPlayerIndexq: 0},
	{WordP2: 0},
	{WordP3: 0},
	{WordP1: 0}
];

self.InstanceType = {
	PlayerChooseBackround: class extends self.ITiledBackgroundInstance {},
	HowManyPlayers: class extends self.ITextInstance {},
	Keyboard: class extends self.IInstance {},
	_3playerBackround: class extends self.ITiledBackgroundInstance {},
	Player1: class extends self.ITextInputInstance {},
	Player2: class extends self.ITextInputInstance {},
	Player3: class extends self.ITextInputInstance {},
	GameBR: class extends self.ITiledBackgroundInstance {},
	Player1Guess: class extends self.ISpriteInstance {},
	Player2Guess: class extends self.ISpriteInstance {},
	Player3Guess: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Player1Word: class extends self.ITiledBackgroundInstance {},
	YourWordIs1: class extends self.ITextInstance {},
	Dictionary: class extends self.IDictionaryInstance {},
	Player2WordBR: class extends self.ITiledBackgroundInstance {},
	YourWordIs2: class extends self.ITextInstance {},
	Player3WordBR: class extends self.ITiledBackgroundInstance {},
	YourWordIs3: class extends self.ITextInstance {},
	Word1: class extends self.ITextInstance {},
	JSON: class extends self.IJSONInstance {},
	Button: class extends self.IButtonInstance {},
	Word2: class extends self.ITextInstance {},
	Word3: class extends self.ITextInstance {},
	P1NAME: class extends self.ITextInstance {},
	InstructionsBR: class extends self.ITiledBackgroundInstance {},
	HowToPlay: class extends self.ITextInstance {},
	H2P1: class extends self.ITextInstance {},
	DontLetAnyoneSee: class extends self.ITextInstance {},
	H2P2: class extends self.ITextInstance {},
	Text: class extends self.ITextInstance {},
	MoveToNext: class extends self.ITextInstance {},
	GoAround: class extends self.ITextInstance {},
	Repeat: class extends self.ITextInstance {},
	Point: class extends self.ITextInstance {},
	Majority: class extends self.ITextInstance {},
	P1: class extends self.ITextInstance {},
	p2: class extends self.ITextInstance {},
	P3: class extends self.ITextInstance {},
	NNext: class extends self.ITextInstance {},
	TankYou: class extends self.ITextInstance {},
	T1: class extends self.ITextInstance {},
	cabybara: class extends self.ISpriteInstance {},
	Bow: class extends self.ISpriteInstance {},
	Gavin: class extends self.ISpriteInstance {},
	Kiss: class extends self.ISpriteInstance {},
	can: class extends self.ISpriteInstance {},
	Name: class extends self.ITextInstance {},
	Lock: class extends self.ISpriteInstance {}
}