const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.scrollto,
		C3.Behaviors.bound,
		C3.Behaviors.Platform,
		C3.Plugins.Keyboard,
		C3.Behaviors.solid,
		C3.Plugins.Mouse,
		C3.Plugins.Text,
		C3.Plugins.Button,
		C3.Behaviors.shadowcaster,
		C3.Plugins.Audio,
		C3.Plugins.TiledBg,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.System.Cnds.OnLayoutStart
	];
};
self.C3_JsPropNameTable = [
	{ScrollTo: 0},
	{BoundTo: 0},
	{Platform: 0},
	{player: 0},
	{Keyboard: 0},
	{Kk: 0},
	{BL: 0},
	{Solid: 0},
	{Sprite: 0},
	{Sprite3: 0},
	{Bedroom: 0},
	{Mouse: 0},
	{Kitchen: 0},
	{Office: 0},
	{Playroom: 0},
	{LivingRoom: 0},
	{Bathoom: 0},
	{bEDROOMLAYOUT: 0},
	{LivingRoomLayout: 0},
	{BathroomLayout: 0},
	{OL: 0},
	{Ll: 0},
	{BrL: 0},
	{KL: 0},
	{PL: 0},
	{PK: 0},
	{BK: 0},
	{KitchenLayout: 0},
	{Lk: 0},
	{Ok: 0},
	{OfficeLayout: 0},
	{PlayRoomLayout: 0},
	{Text: 0},
	{family: 0},
	{TextBubble: 0},
	{Button: 0},
	{FinalKey: 0},
	{ShadowCaster: 0},
	{bathtub: 0},
	{TheBoard: 0},
	{BR: 0},
	{DecoyKey: 0},
	{Sun: 0},
	{Lamp: 0},
	{PRT: 0},
	{MUsic: 0},
	{Books: 0},
	{Br2: 0},
	{ArrowKeys: 0},
	{TiledBackground: 0},
	{StartButton: 0},
	{Bl: 0},
	{Key: 0}
];

self.InstanceType = {
	player: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Kk: class extends self.ISpriteInstance {},
	BL: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Bedroom: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Kitchen: class extends self.ISpriteInstance {},
	Office: class extends self.ISpriteInstance {},
	Playroom: class extends self.ISpriteInstance {},
	LivingRoom: class extends self.ISpriteInstance {},
	Bathoom: class extends self.ISpriteInstance {},
	bEDROOMLAYOUT: class extends self.ISpriteInstance {},
	LivingRoomLayout: class extends self.ISpriteInstance {},
	BathroomLayout: class extends self.ISpriteInstance {},
	OL: class extends self.ISpriteInstance {},
	Ll: class extends self.ISpriteInstance {},
	BrL: class extends self.ISpriteInstance {},
	KL: class extends self.ISpriteInstance {},
	PL: class extends self.ISpriteInstance {},
	PK: class extends self.ISpriteInstance {},
	BK: class extends self.ISpriteInstance {},
	KitchenLayout: class extends self.ISpriteInstance {},
	Lk: class extends self.ISpriteInstance {},
	Ok: class extends self.ISpriteInstance {},
	OfficeLayout: class extends self.ISpriteInstance {},
	PlayRoomLayout: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	family: class extends self.ISpriteInstance {},
	TextBubble: class extends self.ISpriteInstance {},
	Button: class extends self.IButtonInstance {},
	FinalKey: class extends self.ISpriteInstance {},
	bathtub: class extends self.ISpriteInstance {},
	TheBoard: class extends self.ISpriteInstance {},
	BR: class extends self.ISpriteInstance {},
	DecoyKey: class extends self.ISpriteInstance {},
	Sun: class extends self.ISpriteInstance {},
	Platform: class extends self.ISpriteInstance {},
	Lamp: class extends self.ISpriteInstance {},
	PRT: class extends self.ISpriteInstance {},
	MUsic: class extends self.IInstance {},
	Books: class extends self.ITextInstance {},
	Br2: class extends self.ISpriteInstance {},
	ArrowKeys: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	StartButton: class extends self.IButtonInstance {}
}