const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.scrollto,
		C3.Behaviors.EightDir,
		C3.Plugins.Keyboard,
		C3.Behaviors.solid,
		C3.Behaviors.Bullet,
		C3.Behaviors.Sin,
		C3.Plugins.Text,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText
	];
};
self.C3_JsPropNameTable = [
	{ScrollTo: 0},
	{"8Direction": 0},
	{Sprite2: 0},
	{Keyboard: 0},
	{Sprite: 0},
	{Sprite3: 0},
	{Solid: 0},
	{Sprite4: 0},
	{Bullet: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{blue: 0},
	{Sine: 0},
	{Sprite7: 0},
	{invisy: 0},
	{Sprite8: 0},
	{lives: 0},
	{Sprite9: 0},
	{Text2: 0},
	{Text3: 0},
	{Sprite10: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{Text: 0},
	{Lives: 0}
];

self.InstanceType = {
	Sprite2: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	blue: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	invisy: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	lives: class extends self.ITextInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Text2: class extends self.ITextInstance {},
	Text3: class extends self.ITextInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {}
}