const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Button,
		C3.Plugins.LocalStorage,
		C3.Plugins.List,
		C3.Plugins.Shape3D,
		C3.Behaviors.solid,
		C3.Behaviors.shadowcaster,
		C3.Plugins.Camera3D,
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Behaviors.scrollto,
		C3.Behaviors.Car,
		C3.Plugins.Keyboard,
		C3.Behaviors.custom,
		C3.Behaviors.Bullet,
		C3.Plugins.Mouse,
		C3.Behaviors.Pin,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Camera3D.Acts.LookParallelToLayout,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Shape3D.Acts.SetZElevation,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Shape3D.Acts.MoveForward,
		C3.Plugins.Shape3D.Acts.RotateCounterclockwise,
		C3.Plugins.Camera3D.Acts.RotateCamera,
		C3.Plugins.Shape3D.Acts.RotateClockwise,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Camera3D.Acts.SetPosition,
		C3.Plugins.Shape3D.Exps.X,
		C3.Plugins.Shape3D.Exps.Y,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.ToggleBoolInstanceVar,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Behaviors.Car.Acts.SetEnabled,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Shape3D.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Shape3D.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Shape3D.Acts.SetAngle,
		C3.Plugins.Shape3D.Exps.Angle,
		C3.Plugins.Shape3D.Acts.SetZHeight,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Shape3D.Cnds.OnCollision,
		C3.Plugins.Shape3D.Acts.Destroy
	];
};
self.C3_JsPropNameTable = [
	{Save: 0},
	{LocalStorage: 0},
	{List: 0},
	{Solid: 0},
	{ShadowCaster: 0},
	{"3DShape": 0},
	{"3DCamera": 0},
	{TiledBackground: 0},
	{ActivePlayer: 0},
	{ScrollTo: 0},
	{Car: 0},
	{Player: 0},
	{Building2: 0},
	{Keyboard: 0},
	{RoF: 0},
	{Fired: 0},
	{Custom: 0},
	{"3DPlayer": 0},
	{Active: 0},
	{Player2: 0},
	{TiledBackground2: 0},
	{Bullet: 0},
	{Mouse: 0},
	{Pin: 0},
	{"3DShape2": 0}
];

self.InstanceType = {
	Save: class extends self.IButtonInstance {},
	LocalStorage: class extends self.IInstance {},
	List: class extends self.IListInstance {},
	_3DShape: class extends self.I3DShapeInstance {},
	_3DCamera: class extends self.IInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Player: class extends self.ISpriteInstance {},
	Building2: class extends self.I3DShapeInstance {},
	Keyboard: class extends self.IInstance {},
	_3DPlayer: class extends self.I3DShapeInstance {},
	Player2: class extends self.ISpriteInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	Bullet: class extends self.I3DShapeInstance {},
	Mouse: class extends self.IInstance {},
	_3DShape2: class extends self.I3DShapeInstance {}
}