const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Plugins.Button,
		C3.Plugins.Touch,
		C3.Plugins.Sprite,
		C3.Behaviors.DragnDrop,
		C3.Plugins.progressbar,
		C3.Behaviors.Pin,
		C3.Plugins.Text,
		C3.Behaviors.Fade,
		C3.Behaviors.Platform,
		C3.Plugins.Keyboard,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.progressbar.Acts.SetProgress,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Behaviors.Pin.Cnds.IsPinned
	];
};
self.C3_JsPropNameTable = [
	{Solid: 0},
	{StartScreen: 0},
	{BUttonOne: 0},
	{buttontwo: 0},
	{Button4: 0},
	{pet1: 0},
	{pet2: 0},
	{pet3: 0},
	{button3: 0},
	{pet4: 0},
	{dragTo: 0},
	{background: 0},
	{Heath: 0},
	{DragDrop: 0},
	{dogo: 0},
	{Pin: 0},
	{pet1heath: 0},
	{Fade: 0},
	{task: 0},
	{fooofd: 0},
	{water: 0},
	{Text: 0},
	{task2: 0},
	{TiledBackground: 0},
	{bakround: 0},
	{floor134: 0},
	{Platform: 0},
	{person: 0},
	{directions: 0},
	{cat: 0},
	{hamster: 0},
	{Sprite: 0},
	{TiledBackground2: 0},
	{catheathbar: 0},
	{backround4: 0},
	{Heath3: 0},
	{dogheath: 0},
	{catheath: 0},
	{gunieapig: 0},
	{dogheath4: 0}
];

self.InstanceType = {
	StartScreen: class extends self.ITiledBackgroundInstance {},
	BUttonOne: class extends self.ITiledBackgroundInstance {},
	buttontwo: class extends self.ITiledBackgroundInstance {},
	Button4: class extends self.ITiledBackgroundInstance {},
	pet1: class extends self.IButtonInstance {},
	pet2: class extends self.IButtonInstance {},
	pet3: class extends self.IButtonInstance {},
	button3: class extends self.ITiledBackgroundInstance {},
	pet4: class extends self.IButtonInstance {},
	dragTo: class extends self.IInstance {},
	background: class extends self.ISpriteInstance {},
	dogo: class extends self.ISpriteInstance {},
	pet1heath: class extends self.IProgressBarInstance {},
	task: class extends self.ITextInstance {},
	fooofd: class extends self.ITiledBackgroundInstance {},
	water: class extends self.ITiledBackgroundInstance {},
	Text: class extends self.ITextInstance {},
	task2: class extends self.ITextInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	bakround: class extends self.ITiledBackgroundInstance {},
	floor134: class extends self.ITiledBackgroundInstance {},
	person: class extends self.ISpriteInstance {},
	directions: class extends self.IInstance {},
	cat: class extends self.ISpriteInstance {},
	hamster: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	catheathbar: class extends self.IProgressBarInstance {},
	backround4: class extends self.ITiledBackgroundInstance {},
	Heath3: class extends self.IProgressBarInstance {}
}