const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Plugins.Mouse,
		C3.Plugins.Text,
		C3.Behaviors.DragnDrop,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.Destroy
	];
};
self.C3_JsPropNameTable = [
	{Backround: 0},
	{Virus: 0},
	{fridge: 0},
	{tree: 0},
	{bed: 0},
	{soap: 0},
	{StartingBackround: 0},
	{Solid: 0},
	{PlayButton: 0},
	{Instructions: 0},
	{Gamename: 0},
	{Mouse: 0},
	{Backbutton: 0},
	{instructionsbackround: 0},
	{Instructionstext: 0},
	{skybackround: 0},
	{kitchenbackround: 0},
	{bedroombackround: 0},
	{Bathroomwall: 0},
	{homebackbutton: 0},
	{Text: 0},
	{DragDrop: 0},
	{shower: 0},
	{Level: 0},
	{agenda: 0},
	{Cleanlevel: 0},
	{cheeseburger: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{knife: 0},
	{Endingtext: 0},
	{TiledBackground: 0},
	{demonVirus: 0},
	{why: 0},
	{brinstructons: 0},
	{backyardinstructions: 0},
	{hellobnedrom: 0},
	{bathyroominstructions: 0},
	{layout2backround: 0},
	{layout2instructiobs: 0},
	{title: 0},
	{instrutext: 0}
];

self.InstanceType = {
	Backround: class extends self.ITiledBackgroundInstance {},
	Virus: class extends self.ISpriteInstance {},
	fridge: class extends self.ISpriteInstance {},
	tree: class extends self.ISpriteInstance {},
	bed: class extends self.ISpriteInstance {},
	soap: class extends self.ISpriteInstance {},
	StartingBackround: class extends self.ITiledBackgroundInstance {},
	PlayButton: class extends self.ISpriteInstance {},
	Instructions: class extends self.ISpriteInstance {},
	Gamename: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Backbutton: class extends self.ISpriteInstance {},
	instructionsbackround: class extends self.ITiledBackgroundInstance {},
	Instructionstext: class extends self.ITextInstance {},
	skybackround: class extends self.ITiledBackgroundInstance {},
	kitchenbackround: class extends self.ITiledBackgroundInstance {},
	bedroombackround: class extends self.ITiledBackgroundInstance {},
	Bathroomwall: class extends self.ITiledBackgroundInstance {},
	homebackbutton: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	shower: class extends self.ISpriteInstance {},
	Level: class extends self.ITextInstance {},
	agenda: class extends self.ISpriteInstance {},
	Cleanlevel: class extends self.ITextInstance {},
	cheeseburger: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	knife: class extends self.ISpriteInstance {},
	Endingtext: class extends self.ITextInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	demonVirus: class extends self.ISpriteInstance {},
	why: class extends self.ITextInstance {},
	brinstructons: class extends self.ITextInstance {},
	backyardinstructions: class extends self.ITextInstance {},
	hellobnedrom: class extends self.ITextInstance {},
	bathyroominstructions: class extends self.ITextInstance {},
	layout2backround: class extends self.ITiledBackgroundInstance {},
	layout2instructiobs: class extends self.ITextInstance {},
	title: class extends self.ITextInstance {},
	instrutext: class extends self.ITextInstance {}
}