const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.SVGPicture,
		C3.Plugins.Sprite,
		C3.Plugins.Mouse,
		C3.Behaviors.Tween,
		C3.Behaviors.Sin,
		C3.Behaviors.Timer,
		C3.Plugins.TiledBg,
		C3.Plugins.Text,
		C3.Behaviors.DragnDrop,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Text.Acts.SetText,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.CompareVar
	];
};
self.C3_JsPropNameTable = [
	{SVGPicture: 0},
	{start: 0},
	{mouse: 0},
	{moodcheckbg: 0},
	{anxiousbutton: 0},
	{sad: 0},
	{sadbutton: 0},
	{tiredbutton: 0},
	{repeats: 0},
	{Tween: 0},
	{Sine: 0},
	{Timer: 0},
	{anxiousbreathingball: 0},
	{beginanxiousbreathingbutton: 0},
	{welcomebg: 0},
	{welcomebgbg: 0},
	{hdyftxt: 0},
	{anxiousbreatingbg: 0},
	{startanxiousbreathbutton: 0},
	{inhaleexhaleanxi: 0},
	{endoftiredbreathing: 0},
	{endoftiredbreathing2: 0},
	{DragDrop: 0},
	{block: 0},
	{anxiousbreathingbg: 0},
	{anxiousbreathingball1: 0},
	{startanxiousbreathing: 0},
	{anxiousbreathingtxt: 0},
	{keyboard: 0},
	{yellowPuzzlePiece: 0},
	{orangepiece: 0},
	{redpuzzlepiece: 0},
	{bluepuzzlepiece: 0},
	{puzzlebox: 0},
	{timer: 0},
	{puzzletext: 0},
	{wordSearch: 0},
	{castleCircle: 0},
	{puzzlebg: 0},
	{BreathInout: 0},
	{BreathInout2: 0},
	{startText: 0}
];

self.InstanceType = {
	SVGPicture: class extends self.ISVGPictureInstance {},
	start: class extends self.ISpriteInstance {},
	mouse: class extends self.IInstance {},
	moodcheckbg: class extends self.ISpriteInstance {},
	anxiousbutton: class extends self.ISpriteInstance {},
	sad: class extends self.ISpriteInstance {},
	sadbutton: class extends self.ISpriteInstance {},
	tiredbutton: class extends self.ISpriteInstance {},
	anxiousbreathingball: class extends self.ISpriteInstance {},
	beginanxiousbreathingbutton: class extends self.ISpriteInstance {},
	welcomebg: class extends self.ITiledBackgroundInstance {},
	welcomebgbg: class extends self.ISpriteInstance {},
	hdyftxt: class extends self.ISpriteInstance {},
	anxiousbreatingbg: class extends self.ITiledBackgroundInstance {},
	startanxiousbreathbutton: class extends self.ISpriteInstance {},
	inhaleexhaleanxi: class extends self.ITextInstance {},
	endoftiredbreathing: class extends self.ITiledBackgroundInstance {},
	endoftiredbreathing2: class extends self.ITiledBackgroundInstance {},
	block: class extends self.ISpriteInstance {},
	anxiousbreathingbg: class extends self.ITiledBackgroundInstance {},
	anxiousbreathingball1: class extends self.ISpriteInstance {},
	startanxiousbreathing: class extends self.ISpriteInstance {},
	anxiousbreathingtxt: class extends self.ITextInstance {},
	keyboard: class extends self.IInstance {},
	yellowPuzzlePiece: class extends self.ISpriteInstance {},
	orangepiece: class extends self.ISpriteInstance {},
	redpuzzlepiece: class extends self.ISpriteInstance {},
	bluepuzzlepiece: class extends self.ISpriteInstance {},
	puzzlebox: class extends self.ISpriteInstance {},
	timer: class extends self.ITextInstance {},
	puzzletext: class extends self.ITextInstance {},
	wordSearch: class extends self.ISpriteInstance {},
	castleCircle: class extends self.ISpriteInstance {},
	puzzlebg: class extends self.ISpriteInstance {}
}