const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Physics,
		C3.Behaviors.scrollto,
		C3.Plugins.Audio,
		C3.Plugins.Keyboard,
		C3.Plugins.progressbar,
		C3.Plugins.Text,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Physics.Acts.CreateLimitedRevoluteJoint,
		C3.Plugins.progressbar.Acts.SetMaximum,
		C3.Behaviors.Physics.Acts.SetImmovable,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.progressbar.Acts.SetProgress,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Behaviors.Physics.Acts.ApplyImpulseAtAngle,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.Physics.Acts.SetElasticity,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Acts.GoToLayout
	];
};
self.C3_JsPropNameTable = [
	{Kitchen: 0},
	{Solid: 0},
	{Physics: 0},
	{Table: 0},
	{catapultLever: 0},
	{Catapultfram: 0},
	{ScrollTo: 0},
	{Sprite: 0},
	{Audio: 0},
	{Keyboard: 0},
	{Powerbar: 0},
	{Lever2: 0},
	{Frame2: 0},
	{Sprite2: 0},
	{Text: 0},
	{TiledBackground: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Text2: 0},
	{Sprite5: 0},
	{Text3: 0},
	{Text4: 0},
	{Text5: 0},
	{Sprite6: 0},
	{Text6: 0},
	{fired: 0},
	{power: 0}
];

self.InstanceType = {
	Kitchen: class extends self.ITiledBackgroundInstance {},
	Table: class extends self.ISpriteInstance {},
	catapultLever: class extends self.ISpriteInstance {},
	Catapultfram: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Powerbar: class extends self.IProgressBarInstance {},
	Lever2: class extends self.ISpriteInstance {},
	Frame2: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Text2: class extends self.ITextInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Text3: class extends self.ITextInstance {},
	Text4: class extends self.ITextInstance {},
	Text5: class extends self.ITextInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Text6: class extends self.ITextInstance {}
}