const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.EightDir,
		C3.Plugins.TiledBg,
		C3.Plugins.Text,
		C3.Plugins.Keyboard,
		C3.Plugins.Audio,
		C3.Behaviors.Pin,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.MoveAtAngle,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Sprite.Acts.Spawn
	];
};
self.C3_JsPropNameTable = [
	{Solid: 0},
	{"8Direction": 0},
	{"1AdoptMePlayer": 0},
	{Sprite: 0},
	{TiledBackground: 0},
	{cats: 0},
	{EVILDOGS: 0},
	{instructions: 0},
	{welcomescreen: 0},
	{manual: 0},
	{HAVEFUN: 0},
	{lives: 0},
	{catscaught: 0},
	{HowToPlay: 0},
	{keyboard: 0},
	{YOULOSE: 0},
	{presskey: 0},
	{portal: 0},
	{back2: 0},
	{SuperDuperRareCat: 0},
	{wall2: 0},
	{cataudio: 0},
	{BG3: 0},
	{Bkey: 0},
	{Pin: 0},
	{basket: 0},
	{easteregg: 0},
	{playeramerica: 0},
	{captainbasket: 0},
	{YOUWIN: 0},
	{winningBG: 0},
	{gg: 0},
	{winagain: 0},
	{CaptinCat: 0},
	{GGs: 0},
	{arrows: 0},
	{NewBG: 0},
	{catsCaught: 0}
];

self.InstanceType = {
	_1AdoptMePlayer: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	cats: class extends self.ISpriteInstance {},
	EVILDOGS: class extends self.ISpriteInstance {},
	instructions: class extends self.ITiledBackgroundInstance {},
	welcomescreen: class extends self.ITextInstance {},
	manual: class extends self.ITextInstance {},
	HAVEFUN: class extends self.ITextInstance {},
	lives: class extends self.ITextInstance {},
	catscaught: class extends self.ITextInstance {},
	HowToPlay: class extends self.ITextInstance {},
	keyboard: class extends self.IInstance {},
	YOULOSE: class extends self.ITextInstance {},
	presskey: class extends self.ITextInstance {},
	portal: class extends self.ISpriteInstance {},
	back2: class extends self.ITiledBackgroundInstance {},
	SuperDuperRareCat: class extends self.ISpriteInstance {},
	wall2: class extends self.ISpriteInstance {},
	cataudio: class extends self.IInstance {},
	BG3: class extends self.ITiledBackgroundInstance {},
	Bkey: class extends self.ITextInstance {},
	basket: class extends self.ISpriteInstance {},
	easteregg: class extends self.ISpriteInstance {},
	playeramerica: class extends self.ISpriteInstance {},
	captainbasket: class extends self.ISpriteInstance {},
	YOUWIN: class extends self.ITextInstance {},
	winningBG: class extends self.ITiledBackgroundInstance {},
	gg: class extends self.ITextInstance {},
	winagain: class extends self.ITextInstance {},
	CaptinCat: class extends self.ISpriteInstance {},
	GGs: class extends self.ITextInstance {},
	arrows: class extends self.ISpriteInstance {},
	NewBG: class extends self.ITiledBackgroundInstance {}
}