const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Sin,
		C3.Plugins.Keyboard,
		C3.Plugins.Text,
		C3.Plugins.Button,
		C3.Behaviors.Pin,
		C3.Plugins.TiledBg,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.System.Acts.GoToLayout
	];
};
self.C3_JsPropNameTable = [
	{powerMeterBar: 0},
	{Sine: 0},
	{powerneedle: 0},
	{perfectzone: 0},
	{Keyboard: 0},
	{redZone: 0},
	{orangeZone: 0},
	{yellowZone: 0},
	{powerneedle2: 0},
	{instructions: 0},
	{Sprite: 0},
	{Player1: 0},
	{Player2: 0},
	{NextPlayer: 0},
	{Player2button: 0},
	{Playerl: 0},
	{Pin: 0},
	{Pin2: 0},
	{Pin3: 0},
	{hdghfg: 0},
	{TiledBackground2: 0},
	{Button: 0},
	{Text: 0},
	{TiledBackground: 0},
	{powervale2: 0},
	{powervalue: 0},
	{Play2: 0},
	{HEALTH: 0},
	{HEALTH2: 0}
];

self.InstanceType = {
	powerMeterBar: class extends self.ISpriteInstance {},
	powerneedle: class extends self.ISpriteInstance {},
	perfectzone: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	redZone: class extends self.ISpriteInstance {},
	orangeZone: class extends self.ISpriteInstance {},
	yellowZone: class extends self.ISpriteInstance {},
	powerneedle2: class extends self.ISpriteInstance {},
	instructions: class extends self.ITextInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Player1: class extends self.ITextInstance {},
	Player2: class extends self.ITextInstance {},
	NextPlayer: class extends self.IButtonInstance {},
	Player2button: class extends self.IButtonInstance {},
	Playerl: class extends self.ISpriteInstance {},
	hdghfg: class extends self.ISpriteInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	Button: class extends self.IButtonInstance {},
	Text: class extends self.ITextInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {}
}