const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.solid,
		C3.Behaviors.Pathfinding,
		C3.Plugins.Text,
		C3.Behaviors.Sin,
		C3.Plugins.Keyboard,
		C3.Plugins.System.Cnds.Every,
		C3.Behaviors.Pathfinding.Acts.FindPath,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Pathfinding.Cnds.OnPathFound,
		C3.Behaviors.Pathfinding.Acts.StartMoving,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.GoToLayout
	];
};
self.C3_JsPropNameTable = [
	{TiledBackground2: 0},
	{Platform: 0},
	{ScrollTo: 0},
	{ball: 0},
	{Spaceusedasstrokes: 0},
	{Solid: 0},
	{Spaceusedasstrokes2: 0},
	{Sprite: 0},
	{Pathfinding: 0},
	{Sprite2: 0},
	{startrails11h_hambsch_f: 0},
	{d7bwkvv58263781f5f641158f12d022a5ba69f: 0},
	{Text: 0},
	{vibrantgreenauroraborealisovericyarcticwaters: 0},
	{download: 0},
	{download2: 0},
	{spacegalaxytracke291a: 0},
	{world2: 0},
	{Text2: 0},
	{Sprite3: 0},
	{Sine: 0},
	{Sprite4: 0},
	{images: 0},
	{images2: 0},
	{Keyboard: 0},
	{download3: 0},
	{streamoflight021454341492HzO: 0},
	{download4: 0},
	{Sprite5: 0},
	{download5: 0},
	{download6: 0},
	{download7: 0},
	{download8: 0},
	{Text3: 0},
	{download9: 0},
	{download10: 0},
	{Text4: 0},
	{Text5: 0}
];

self.InstanceType = {
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	ball: class extends self.ISpriteInstance {},
	Spaceusedasstrokes: class extends self.ISpriteInstance {},
	Spaceusedasstrokes2: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	startrails11h_hambsch_f: class extends self.ISpriteInstance {},
	d7bwkvv58263781f5f641158f12d022a5ba69f: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	vibrantgreenauroraborealisovericyarcticwaters: class extends self.ISpriteInstance {},
	download: class extends self.ISpriteInstance {},
	download2: class extends self.ISpriteInstance {},
	spacegalaxytracke291a: class extends self.ISpriteInstance {},
	world2: class extends self.ITextInstance {},
	Text2: class extends self.ITextInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	images: class extends self.ISpriteInstance {},
	images2: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	download3: class extends self.ISpriteInstance {},
	streamoflight021454341492HzO: class extends self.ISpriteInstance {},
	download4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	download5: class extends self.ISpriteInstance {},
	download6: class extends self.ISpriteInstance {},
	download7: class extends self.ISpriteInstance {},
	download8: class extends self.ISpriteInstance {},
	Text3: class extends self.ITextInstance {},
	download9: class extends self.ISpriteInstance {},
	download10: class extends self.ISpriteInstance {},
	Text4: class extends self.ITextInstance {},
	Text5: class extends self.ITextInstance {}
}