const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Button,
		C3.Plugins.Text,
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Behaviors.Sin,
		C3.Behaviors.Orbit,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Sin.Cnds.IsEnabled,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Button.Acts.Destroy,
		C3.Plugins.Text.Acts.Destroy
	];
};
self.C3_JsPropNameTable = [
	{StartGameButton: 0},
	{coins: 0},
	{HappyLvl: 0},
	{TiledBackground: 0},
	{startText: 0},
	{hidden: 0},
	{Sine: 0},
	{landanimal: 0},
	{Landcollectpets: 0},
	{ShopButton: 0},
	{Transferwateranimals: 0},
	{trensferlandanimal: 0},
	{transferairanimals: 0},
	{TiledBackground2: 0},
	{fishhiden: 0},
	{Orbit: 0},
	{wateranimals: 0},
	{birdhidden: 0},
	{airAnimal: 0},
	{Touch: 0},
	{Shopland1: 0},
	{shopwater1: 0},
	{airupgrade1: 0},
	{buyfood: 0},
	{foods: 0},
	{LandBackground: 0},
	{ShopBackground: 0},
	{FOOD: 0},
	{catchland: 0},
	{catchwater: 0},
	{catchair: 0},
	{Lasso: 0},
	{Fishrod: 0},
	{net: 0},
	{Audio: 0},
	{TiledBackground3: 0},
	{bagoffood: 0},
	{gameoverscreen: 0},
	{PlayAgain: 0},
	{Catchanimals: 0},
	{lassoshop: 0},
	{Fishingrodshop: 0},
	{netshop: 0},
	{instruct: 0},
	{insrtuctdestroy: 0},
	{click: 0},
	{snakehidden: 0},
	{snake: 0},
	{hamhidden: 0},
	{hams: 0},
	{octohidden: 0},
	{octo: 0},
	{sharkhidden: 0},
	{shark: 0},
	{butterhidden: 0},
	{butter: 0},
	{dragonhidden: 0},
	{dragon: 0},
	{in: 0},
	{Text: 0},
	{Win: 0},
	{YouWin: 0},
	{Coins: 0},
	{happiness: 0},
	{foodPacks: 0},
	{FISHROD: 0},
	{LASSO: 0},
	{NET: 0},
	{HorseHidden: 0}
];

self.InstanceType = {
	StartGameButton: class extends self.IButtonInstance {},
	coins: class extends self.ITextInstance {},
	HappyLvl: class extends self.ITextInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	startText: class extends self.ITextInstance {},
	landanimal: class extends self.ISpriteInstance {},
	Landcollectpets: class extends self.IButtonInstance {},
	ShopButton: class extends self.IButtonInstance {},
	Transferwateranimals: class extends self.IButtonInstance {},
	trensferlandanimal: class extends self.IButtonInstance {},
	transferairanimals: class extends self.IButtonInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	wateranimals: class extends self.ISpriteInstance {},
	airAnimal: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Shopland1: class extends self.IButtonInstance {},
	shopwater1: class extends self.IButtonInstance {},
	airupgrade1: class extends self.IButtonInstance {},
	buyfood: class extends self.IButtonInstance {},
	foods: class extends self.ITextInstance {},
	LandBackground: class extends self.ITiledBackgroundInstance {},
	ShopBackground: class extends self.ITiledBackgroundInstance {},
	FOOD: class extends self.IButtonInstance {},
	catchland: class extends self.ISpriteInstance {},
	catchwater: class extends self.ISpriteInstance {},
	catchair: class extends self.ISpriteInstance {},
	Lasso: class extends self.ITextInstance {},
	Fishrod: class extends self.ITextInstance {},
	net: class extends self.ITextInstance {},
	Audio: class extends self.IInstance {},
	TiledBackground3: class extends self.ITiledBackgroundInstance {},
	bagoffood: class extends self.ITiledBackgroundInstance {},
	gameoverscreen: class extends self.ITiledBackgroundInstance {},
	PlayAgain: class extends self.IButtonInstance {},
	Catchanimals: class extends self.ITiledBackgroundInstance {},
	lassoshop: class extends self.ITiledBackgroundInstance {},
	Fishingrodshop: class extends self.ITiledBackgroundInstance {},
	netshop: class extends self.ITiledBackgroundInstance {},
	instruct: class extends self.ITextInstance {},
	insrtuctdestroy: class extends self.IButtonInstance {},
	click: class extends self.ITextInstance {},
	snake: class extends self.ISpriteInstance {},
	hams: class extends self.ISpriteInstance {},
	octo: class extends self.ISpriteInstance {},
	shark: class extends self.ISpriteInstance {},
	butter: class extends self.ISpriteInstance {},
	dragon: class extends self.ISpriteInstance {},
	in: class extends self.ITextInstance {},
	Text: class extends self.ITextInstance {},
	Win: class extends self.ITiledBackgroundInstance {},
	YouWin: class extends self.ITextInstance {}
}