const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Camera3D,
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Plugins.Model3D,
		C3.Plugins.Tilemap,
		C3.Behaviors.scrollto,
		C3.Behaviors.Car,
		C3.Behaviors.Bullet,
		C3.Behaviors.solid,
		C3.Behaviors.Physics,
		C3.Plugins.Keyboard,
		C3.Plugins.LocalStorage,
		C3.Behaviors.Turret,
		C3.Plugins.Button,
		C3.Behaviors.Anchor,
		C3.Plugins.Text,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Behaviors.Car.Acts.Stop,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.Turret.Acts.AddTarget,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Behaviors.Turret.Acts.AcquireTarget,
		C3.Behaviors.Turret.Cnds.OnShoot,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Acts.SetVar
	];
};
self.C3_JsPropNameTable = [
	{"3DCamera": 0},
	{TiledBackground: 0},
	{Sprite: 0},
	{"3DModel": 0},
	{TiledBackground2: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{TiledBackground3: 0},
	{Tilemap: 0},
	{Tilemap2: 0},
	{Tilemap3: 0},
	{Tilemap4: 0},
	{Tilemap5: 0},
	{Tilemap6: 0},
	{cahosModeOn: 0},
	{Sprite4: 0},
	{score: 0},
	{ScrollTo: 0},
	{Car: 0},
	{Sprite5: 0},
	{TiledBackground4: 0},
	{Sprite6: 0},
	{Bullet: 0},
	{Sprite7: 0},
	{Solid: 0},
	{Physics: 0},
	{Sprite8: 0},
	{Keyboard: 0},
	{LocalStorage: 0},
	{Turret: 0},
	{Sprite9: 0},
	{Anchor: 0},
	{Button: 0},
	{LINE: 0},
	{LAPS: 0},
	{Sprite10: 0},
	{LAPS2: 0}
];

self.InstanceType = {
	_3DCamera: class extends self.IInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Sprite: class extends self.ISpriteInstance {},
	_3DModel: class extends self.I3DModelInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	TiledBackground3: class extends self.ITiledBackgroundInstance {},
	Tilemap: class extends self.ITilemapInstance {},
	Tilemap2: class extends self.ITilemapInstance {},
	Tilemap3: class extends self.ITilemapInstance {},
	Tilemap4: class extends self.ITilemapInstance {},
	Tilemap5: class extends self.ITilemapInstance {},
	Tilemap6: class extends self.ITilemapInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	TiledBackground4: class extends self.ITiledBackgroundInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Button: class extends self.IButtonInstance {},
	LINE: class extends self.ISpriteInstance {},
	LAPS: class extends self.ITextInstance {},
	Sprite10: class extends self.ISpriteInstance {}
}